### ISSUE TITLE
Tab themes

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1009]
Setting to choose predefined themes. It may require add extra settings to add more design flexibility.

**Comment by htmgarcia** [comment]
@stevejburge current progress:

Themes styles by using a preset approach (pre configured settings, so the user can use a theme base and modify colors, spacing if desired):
![Screen Shot 2023-01-26 at 16 55 11](https://user-images.githubusercontent.com/4999794/214969121-7c693eb2-6a5e-41e6-ad9e-bd1095e310e3.png)

![Screen Shot 2023-01-26 at 16 55 57](https://user-images.githubusercontent.com/4999794/214969287-36dbec1e-5c9b-484e-aed7-bab2616731ab.png)

**Comment by stevejburge** [comment]
That's great progress, thanks @htmgarcia
