### ISSUE TITLE
Blocks with "Advanced" in the name are not listed as first

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1018]
When inserting a new block, Advanced Image, Advanced Tabs, etc are not listed in first results when skipping "advanced" word:
![Screen Shot 2022-07-07 at 13 20 50](https://user-images.githubusercontent.com/4999794/177842642-64d4b975-e20e-4000-baa9-f99f6a6ef1b6.png)

See if we can push them to first search results.

**Comment by htmgarcia** [comment]
@stevejburge what about renaming those blocks, so the key word (image, video, button, icon, etc) is listed first? 
As example: "Advanced Image" becomes "Image _Something_"

**Comment by stevejburge** [comment]
@htmgarcia Makes sense. Two ideas:

Image (PublishPress)
Image (Advanced)

**Comment by htmgarcia** [comment]
@stevejburge I like more the first one, however the closing parentheses jumps to a new line and looks odd ![Screen Shot 2022-07-08 at 10 58 15](https://user-images.githubusercontent.com/4999794/178028290-dece5e4b-b332-4227-8a2f-c2200464d662.png)

Second suggestion looks fine:
![Screen Shot 2022-07-08 at 11 00 52](https://user-images.githubusercontent.com/4999794/178028707-306643b7-d7e6-4526-a635-4b79d421bf56.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

Would it be best to remove the ( ) characters?

**Comment by stevejburge** [comment]
Thanks. Should we standardize the names, perhaps using the 2nd approach?

**Comment by htmgarcia** [comment]
@stevejburge for all the blocks? I like the idea

**Comment by stevejburge** [comment]
@htmgarcia. Thanks. Your thoughts on this? Something like "Login/Register Form PublishPress" could be 3 or 4 lines, right? Probably not ideal

**Comment by htmgarcia** [comment]
@stevejburge we can make short the long names. As example:

- "Login/Register (PublishPress)"
- "Columns (PublishPress)"
- "Tabs (PublishPress)"
- "Accordions (PublishPress)"

For reference CoBlocks plugin:
![Screen Shot 2022-07-25 at 14 13 06](https://user-images.githubusercontent.com/4999794/180856411-c25677d7-60d0-45eb-8ddf-9cc2bd004bae.png)

**Comment by stevejburge** [comment]
@htmgarcia That sounds like the best solution

**Comment by htmgarcia** [comment]
@stevejburge almost there. The closing parentheses doesn't look good.
![Screen Shot 2022-09-30 at 14 26 58](https://user-images.githubusercontent.com/4999794/193342736-a981889e-3c2c-4445-ac6c-287eebb67ca4.png)
