### ISSUE TITLE
Move admin content to individual pages

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1026]
Block Access, Settings, Custom styles, etc. each one should have its own page to not load all the assets from all the features at once.
![Screen Shot 2022-07-15 at 16 10 47](https://user-images.githubusercontent.com/4999794/179311181-c360d90d-9e53-48fb-bbaa-f35fc76b00fb.png)

**Comment by stevejburge** [comment]
That make sense. It would be good to make this plugin's UI closer to the rest of PublishPress
