### ISSUE TITLE
Translations Updates for Spanish-Italian and French

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Blocks#1035]
Hi,
Here's the Spanish-Italian and French translations updates to be added into plugin language folder
[Blocks-TranslationUpdatesFr-Es-It-July28_2022.zip](https://github.com/publishpress/PublishPress-Blocks/files/9211854/Blocks-TranslationUpdatesFr-Es-It-July28_2022.zip)
Best,
Angelo

**Comment by htmgarcia** [comment]
Thanks @wocmultimedia !
