### ISSUE TITLE
Block controls management

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1036]
Edit: manage Block controls similar to Permissions but without User role dropdown.

As example: Editors can only add block controls to paragraphs and heading blocks.

**Comment by stevejburge** [comment]
@htmgarcia great idea

**Comment by htmgarcia** [comment]
@stevejburge I made some arrangements in the code for coming version (2.14.1) to make the implementation of this feature easier, however we would need to tackle this one first #1026 I appreciate your opinion.

**Comment by stevejburge** [comment]
Would be great to have "Block Controls" as a menu item at this point

**Comment by htmgarcia** [comment]
@stevejburge current progress:
![Screen Shot 2022-10-12 at 15 04 37](https://user-images.githubusercontent.com/4999794/195437249-2cf941ce-0d82-456c-b62b-83f08af47965.png)
![Screen Shot 2022-10-12 at 15 04 06](https://user-images.githubusercontent.com/4999794/195437245-1b4e05fc-eb61-466a-abec-0853fe351518.png)

**Comment by stevejburge** [comment]
Great solution, thanks @htmgarcia
