### ISSUE TITLE
unable to crop image using crop tool bar from advanced accordion 

### ISSUE THREAD

**Issue by franpiper** [publishpress/PublishPress-Blocks#1050]
When using Crop tool from Tool Bar Menu in Accordion item, image can not be manually cropped
Post>Advanced Accordion>Accordion Item>Image from web
right click on image, selected crop from tool bar menu
excepted to be able to manually crop off edges of image
![Unable to Crop Image](https://user-images.githubusercontent.com/108231635/182004420-84158335-4d2a-4818-912f-bbc848767e43.PNG)

**Comment by htmgarcia** [comment]
Hi @franpiper, to crop an image please follow these guidelines: https://watchful.net/how-to/edit-crop-wordpress-images/

In particular this step:

> After clicking the “Crop” icon, you’ll see three options:
> 
> - Zoom (the search icon)
> - Aspect Ratio (the picture icon)
> - Rotate (the circular arrow icon)
