### ISSUE TITLE
appearance issue in advanced TAB after adding multiple images

### ISSUE THREAD

**Issue by franpiper** [publishpress/PublishPress-Blocks#1051]
appearance issue using advanced tab and multiple images, when visiting site the tab appearance confusing to start with, then when moving thur the attached image are generated and you can understand the tab

## Expected Behavior
 
I expected to see the first image in tab with the arrows indicating there are more images

## Current Behavior

it appears to have text cutoff when first viewing the tab area, your trying to see what it should read missing the fact that there are multiple image in this tab. Unsure if issue can be from the first image I used from my library was a large, I reduced the image however still found the issue.

![Appearance issue in TAB](https://user-images.githubusercontent.com/108231635/182046842-3b859501-72bd-4092-bfce-b220d9f1fdb6.PNG)

## Your Environment

* Version used:
* Browser Name and version: Mircosoft Edge  version 103.0.1264.77 (Official build) (64-bit)
* Operating System and version (desktop or mobile): desktop, windows 10
* Link to your project:

**Comment by htmgarcia** [comment]
Hi @franpiper,
it seems you are using an Image slider block inside one of the tabs, correct? We fixed this issue in a recent release. Please update PublishPress Blocks to version 2.14.1. If the issue continues, please share the most possible details.
