### ISSUE TITLE
Allow translation of texts in block

### ISSUE THREAD

**Issue by ChristopheCaron** [publishpress/publishpress-blocks#1062]
As described in this issue: https://wordpress.org/support/topic/allow-translation-for-default-header-text/

- [ ] Allow to translate "Header text" in wp-content/plugins/advanced-gutenberg/assets/blocks/blocks.js:6410

- [ ] Allow to translate "Tab header" in wp-content/plugins/advanced-gutenberg/assets/blocks/blocks.js:12750

This two terms are displayed in back office which webmaster used other languages, others blocks options are translated but not this one.

Thanks.

**Comment by htmgarcia** [comment]
Thanks @ChristopheCaron ! We already took care of this. It will be available in the next release.
https://github.com/publishpress/PublishPress-Blocks/commit/2106db8c86a8e110c269ed976c87e4648b4c0554
https://github.com/publishpress/PublishPress-Blocks/commit/6ded49b66c135b0bd99846153149c961379a85ad
