### ISSUE TITLE
Make accordion auto expand when anchor link is in the same page

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1068]
Label: Feature request

Currently, "Advanced Accordion" blocks (PRO) have anchor features. However, upon clicking the anchor link, it is not automatically expand the accordion item.

It will be greater if whenever the anchor link is clicked, it will also expand the accordion item.

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/77c62002bb0e0a82d2aedd0587eeaee09d6f701c
