### ISSUE TITLE
Small text changes to settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#1069]
- "Data Export" for the tab name
- Should "Google API key" be under a "Maps" tab?
- "Remove autop" this can be the last item on the General tab.
- The "Remove autop" explanation isn't clear. Why should people use this?
- Is #5952de the PublishPress color?

<img width="807" alt="Screen Shot 2022-09-29 at 11 11 47 AM" src="https://user-images.githubusercontent.com/3868028/193070022-bd10a270-f1c6-4b6e-be98-bd632d100af7.png">

**Comment by htmgarcia** [comment]
@stevejburge 
![Screen Shot 2022-09-29 at 13 58 10](https://user-images.githubusercontent.com/4999794/193119015-b57f579f-bf27-4639-b832-57dd502098a4.png)

> The "Remove autop" explanation isn't clear. Why should people use this?

Is a feature that seems to apply only to Classic editor for content that is not wrapped by `<p> `tags and to Classic editor block in Gutenberg. 

Can't confirm, but may apply also to other post contents that are not wrapped by `<div>` or `<p>` tags.

> Is #5952de the PublishPress color?

That is the default color for icons from the original plugin. I updated to use PP brand color as default.

**Comment by stevejburge** [comment]
@htmgarcia Yes, confusing :) Do we need this setting?

**Comment by htmgarcia** [comment]
@stevejburge I would recommend to disable the setting for now and if no user complains about it, we can safely remove permanently later.

**Comment by htmgarcia** [comment]
By disable I means make it invisible to configure.

**Comment by stevejburge** [comment]
Sounds good to me
