### ISSUE TITLE
Adv Column and Columns Manager

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#107]
@htmgarcia Any idea if we need both of these in the Default Blocks Config?

![Screen Shot 2020-08-10 at 11 46 54 AM](https://user-images.githubusercontent.com/3868028/89802297-57a26e80-daff-11ea-9dbf-0343957cf1df.png)

**Comment by htmgarcia** [comment]
Yes, (1) columns manager wraps the (2) advanced columns. Each block type has its own settings and I confirm the settings works:
<img width="664" alt="Screen Shot 2020-08-12 at 12 52 54" src="https://user-images.githubusercontent.com/4999794/90049707-d1229400-dc9a-11ea-8886-2e1109e2f1a0.png">

**Comment by htmgarcia** [comment]
@stevejburge
