### ISSUE TITLE
Small text changes to Dashboard

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#1070]
- Enable extra blocks including content displays, sliders, buttons, icons, tabs, accordions, and more.
- If some blocks are not listed in Block Permissions, try enabling this feature.
- Add Google Fonts support to core blocks including paragraphs and headings.
- Should we rename "Custom Styles" to "Block Styles"?

<img width="1104" alt="Screen Shot 2022-09-29 at 11 21 19 AM" src="https://user-images.githubusercontent.com/3868028/193072339-787a2bbc-001f-4410-982d-5aa28322675b.png">

**Comment by htmgarcia** [comment]
@stevejburge agree. "Block Styles" sounds better.
![Screen Shot 2022-09-29 at 15 39 52](https://user-images.githubusercontent.com/4999794/193137574-7f6d3ace-22ea-4949-a47f-5937c66b37aa.png)
