### ISSUE TITLE
Review vendor constant name

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1082]
https://github.com/publishpress/PublishPress-Blocks/blob/master/src/advanced-gutenberg.php#L44-L46
https://github.com/publishpress/PublishPress-Blocks-Pro/blob/main/src/advanced-gutenberg-pro.php#L20-L22

**Comment by htmgarcia** [comment]
@andergmartins about [Instance protection](https://github.com/publishpress/publishpress-instance-protection), I tested cases with Blocks Free enabled only, Blocks Pro enabled only and both Free and Pro enabled. Always calls:
```
$includeFilebRelativePath = '/publishpress/publishpress-instance-protection/include.php';
if (file_exists(__DIR__ . '/vendor' . $includeFilebRelativePath)) {
    require_once __DIR__ . '/vendor' . $includeFilebRelativePath;
}
```
In which scenario this would be executed?
```
else if (defined('PP_AUTHORS_VENDOR_PATH') && file_exists(PP_AUTHORS_VENDOR_PATH . $includeFilebRelativePath)) {
    require_once PP_AUTHORS_VENDOR_PATH . $includeFilebRelativePath;
}
```

I appreciate your comments!

**Comment by andergmartins** [comment]
@htmgarcia the constant `PP_AUTHORS_VENDOR_PATH` on this case, is used to allow users that use Composer in a global level in the site to change where vendor is located. In the past a user requested to be able to use composer to install our plugin, and on this case, the vendor folder won't be find inside the /var/www/html/wp-content/plugins/publishpress-authors/vendor dir, but probably on /var/www/vendor, or other hidden location.

**Comment by htmgarcia** [comment]
Fixed 
https://github.com/publishpress/PublishPress-Blocks/commit/7eb702e8e96c9a4b4f0d2ebb26edf36579ec8675#diff-e28586f587e52378438c261f749e6208f0b371f7d8fb9593d1598cac0b5ae10b
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/6112b718bcd1988dcdaf821f1475a63b8e02dd5e
