### ISSUE TITLE
All blocks allowed for user role regardless of Block Permissions (fix included)

### ISSUE THREAD

**Issue by igrginov** [publishpress/PublishPress-Blocks#1084]
**Describe the bug**
A user has access to all blocks, irregardless of Block Permission settings. This seems to happen because of the check in `getUserBlocksForGutenberg()` inside `advanced-gutenberg-main.php` which checks if `core/legacy-widget` is in `$advgb_blocks_user_roles['active_blocks']` for a particular role.

If it is, it incorrectly removes all keys from `$advgb_blocks_user_roles['inactive_blocks']` (rather than just the one with `core/legacy-widget` - which is I assume the intended behavior).

Then you end up with `$advgb_blocks_user_roles['inactive_blocks']` being an empty array.

This is a problem because that array is then localized (`advanced-gutenberg-main.php:567`) and used in the editor. And in `editor.js` there's the following snippet that basically allows all blocks if they're not specifically defined in the `inactive_blocks` array (the default condition / last `else`):

```js
                    // Compare current block with the list of blocks we have
                    //...
                    } else {
                        // This block is not in our database yet, but by default we allow the usage
                        granted_blocks.push(blocks[block].name);
                        missing_block = true;
                    }
```

**THE FIX**

In `advanced-gutenberg-main.php:3286` (`getUserBlocksForGutenberg()` ):

Just need to do this:

```php
                        foreach ($advgb_blocks_user_roles['inactive_blocks'] as $key => $type) {
                            if ($type === 'core/legacy-widget') {
                                unset($advgb_blocks_user_roles['inactive_blocks'][$key]);
                            }
                        }
```

Instead of this (how it is currently):

```php
                        foreach ($advgb_blocks_user_roles['inactive_blocks'] as $key => $type) {
                            if (in_array('core/legacy-widget', $advgb_blocks_user_roles['inactive_blocks'])) {
                                unset($advgb_blocks_user_roles['inactive_blocks'][$key]);
                            }
                        }
```

This will just remove the single key (i.e. remove `core/legacy-widget` from `inactive_blocks` key) rather than *ALL* keys if it finds `core/legacy-widget` in `inactive_blocks`.

**To Reproduce**
See above, haven't tested on a fresh install but I assume you could just:
1. Enable / disable some blocks for a specific user role
2. Have `core/legacy-widget` as part of your `inactive_blocks` (not sure if this is even possible on a fresh install since `core/legacy-widget` is grayed out, we migrated from 2.x.x so maybe this was a leftover from back when)
3. When you try to edit a post as a user from that role, you should have access to all blocks, regardless of what you enabled / disabled in step 1

**Expected behavior**
That toggling Block Permission works

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome but not relevant
 - Version Not relevant

**Plugin version**
Latest at the time of writing which was `3.0.1` (happens in `3.0.0` as well)

**Additional context**
Would be reaaaally nice if this could make it into `3.0.2` 🙏

**Comment by htmgarcia** [comment]
I was able to reproduce the issue.
Thanks for the valuable feedback and fix suggestion, @igrginov !
