### ISSUE TITLE
Support Cloud-based Maps Styling

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1088]
> t would be really helpful if the PublishPress Blocks Google Maps block also supported Google Cloud-based maps styling, which is the new standard for styling Google Maps. Currently one has to paste styles into a text field, there is no way for specifying a style ID.

For reference: https://developers.google.com/maps/documentation/cloud-customization/overview

Ticket: 169756

**Comment by htmgarcia** [comment]
@stevejburge this maps seems to be a paid feature
![Screen Shot 2022-10-27 at 13 40 35](https://user-images.githubusercontent.com/4999794/198372265-f06a2c83-3581-4df4-81d5-dc7e8a6fe092.png)
