### ISSUE TITLE
PRO_BLOCKS_ES-FR-IT-TranslationUpdate_October2022 and sugegstions

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Blocks#1094]
Hi,

1- I have made the translation of Block PRO using the inside languages files that had some strings not translated. However inside the Pro plugin language folder there's no file.pot. I made some test using a Button block and I saw that still some strings are not translated, maybe they are overridden by some other plugins, but in any case such strings are not present in the files I translated.
2- I saw that the plugin folder is named "advanced-gutenberg-pro" but the language files are named as the free version (e.g. advanced-gutenberg-it_IT.po). Maybe it would be better also check this filename which can affect the translation visualization.
3- Here's the ES-FR-IT translation updated according with what was inside the folder. I created the json file with a converter and renamed a the old one present in the folder
[PRO_BLOCKS_ES-FR-IT-TranslationUpdate_October2022.zip](https://github.com/publishpress/PublishPress-Blocks/files/9858633/PRO_BLOCKS_ES-FR-IT-TranslationUpdate_October2022.zip)

Thanks,
Angelo

**Comment by htmgarcia** [comment]
Thanks @wocmultimedia ! I attach the most recent PO and POT files of both versions. Please translate these.
[free.zip](https://github.com/publishpress/PublishPress-Blocks/files/9863662/free.zip)
[pro.zip](https://github.com/publishpress/PublishPress-Blocks/files/9863663/pro.zip)
No need to create the JSON files. I generate them from PO through terminal.

The language files from Pro version are not available in the installation plugin file. We translate them and later merge with Free translations through terminal, so we can use the same text domain.

**Comment by wocmultimedia** [comment]
Hi Valentin,

Thank you very much for accepting my suggestions for the pro filename and making a new polished file.pot and languages folder.
Here's the New ES-FR-IT Translations reviewed for Pro and Free

We should do the same for the whole plugins, so we'll have a clean and well translated language folder
[PRO_advanced-gutenberg_NewTranslationsES-FR-IT_October26.zip](https://github.com/publishpress/PublishPress-Blocks/files/9868309/PRO_advanced-gutenberg_NewTranslationsES-FR-IT_October26.zip)

[FREE_advanced-gutenberg_NewTranslationsES-FR-IT_October26.zip](https://github.com/publishpress/PublishPress-Blocks/files/9868316/FREE_advanced-gutenberg_NewTranslationsES-FR-IT_October26.zip)

Regards,
Angelo

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/0aabf5f585cc8a3ff2e431c6c14ed2d75557a9c3
