### ISSUE TITLE
Interferes with core buttons

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1103]
> The Advanced Gutenberg styles interfere with the core/buttons horizontal alignment:
> The core/button blocks inside break instead of staying in the same row.
> Then the horizontal alignment options (left, right, space between, justified) don’t have any effect.
> 
> The reason for this are these styles that are added by the Advanced Gutenberg blocks.css stylesheet:

`.editor-styles-wrapper .wp-block .wp-block {
  max-width: 100%;
  width: 100%;
}`

Original thread: https://wordpress.org/support/topic/interferes-with-core-buttons-horizontal-alignment/

Based on my test, I can replicate with this step to reproduce:
1. Add button (default button from Gutenberg)
2. Change width setting to 25%
3. Observe issue that it will 100% instead
4. Try change the alignment, and it will not work
![image](https://user-images.githubusercontent.com/83811723/200353550-d750fa21-e631-4ea4-bbe1-274796608035.png)
![image](https://user-images.githubusercontent.com/83811723/200353580-4ef80154-7f2e-446b-a8b4-24f62bf57055.png)

**Comment by htmgarcia** [comment]
@rizaardiyanto1412 I'm not able to reproduce. May you test again under WP 6.1.1, please?

**Comment by htmgarcia** [comment]
@rizaardiyanto1412 please disregard previous message. The fix for #1107 also fix this issue.
