### ISSUE TITLE
Can't Select list item

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1107]
When having PP Blocks activated, it almost impossible to select list item (default element from Gutenberg). 

Step to replicate:
1. Install PP Block
2. Add list item (from Gutenberg)
3. Try add some word
4. Try to change the style (e.g. bold) for the word in middle
5. You will find it difficult
6. Try deactivate PP Block
7. Try change the style again
8. You will find it very easy

**Comment by htmgarcia** [comment]
I confirm the issue. It happens in WP 6.1
