### ISSUE TITLE
Amount of strings not coinciding between folder and wp-system

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Blocks#1143]
Hi Steve,
I was making the translation update of Gutenberg when I discovered that the file pot inside the languages folder has 1205 strings as well as each single language with about 59 strings to be translated. 
But when I visited the plugin translation page in WordPresss it has only 445 strings. 
https://translate.wordpress.org/projects/wp-plugins/advanced-gutenberg/stable/
What's going on? How do I have to proceed?
Thanks for your reply.
Angelo

**Comment by htmgarcia** [comment]
Continue in #1145
