### ISSUE TITLE
PRO and FREE version have the same languages file .po

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Blocks#1153]
Hi Steve,

I just made a check and the PRO languages folder have the same o/mo files of FREE languages folder. Is it correct?
No file pot is inside the PRO languages folder.
Please, let me know about it.

Thanks
Angelo

**Comment by htmgarcia** [comment]
@wocmultimedia I duplicate those from Free, so later merge with the Pro ones located in source folder: https://github.com/publishpress/PublishPress-Blocks-Pro/tree/main/src/languages/source

Please only check the ones from the link above.

**Comment by htmgarcia** [comment]
@wocmultimedia to complement, please only check this ones:

- Free: https://github.com/publishpress/PublishPress-Blocks/tree/master/src/languages
- Pro: https://github.com/publishpress/PublishPress-Blocks-Pro/tree/main/src/languages/source

**Comment by wocmultimedia** [comment]
Hi,
I wish you can better explain me what happen, because I wrote my issue in consideration of what I found in my local Pro languages folder. As you can see from this screenshot just taken two minute before.
![pro-local-languages-folder](https://user-images.githubusercontent.com/2352240/213763116-12b10abf-2f56-4c2f-acc5-23fbaf1e4cf5.jpg)

According to your above reply, what do I have to do? Do I have to download this Pro version or what?
Thanks for let me understood
Angelo

**Comment by htmgarcia** [comment]
Hi @wocmultimedia 

> I just made a check and the PRO languages folder have the same o/mo files of FREE languages folder. Is it correct?

The PO filenames are the same in the finals Free and Pro versions (like in your screenshot). 

Please ignore the final versions (like in your screenshot). That can lead to confusion. Only use the PO files from the Github repositories from master or main branch:

- Free: https://github.com/publishpress/PublishPress-Blocks/tree/master/src/languages
- Pro: https://github.com/publishpress/PublishPress-Blocks-Pro/tree/main/src/languages/source

We just added you to Pro repository. Please let me know if you can access or if you have questions.

**Comment by wocmultimedia** [comment]
Hi,
I understand and also checked the free languages folder, it has to be updated with the new files I sent you and which I enclose here again. Because I updated the few strings still appearing untranslated in the folder.

[Blocks-ES-FR-IT-TranslationsUpdates_January2023.zip](https://github.com/publishpress/PublishPress-Blocks/files/10468985/Blocks-ES-FR-IT-TranslationsUpdates_January2023.zip)

Besides, with @ojopaul we made an agreement that he will refresh each single language in the languages folder of the plugins new versions. So when I update the plugin to latest version, I will translate what is inside the languages folder and then compare with the translation in WP-System. This is good for free version but also for the Pro one. Using this method will avoid that I can make a mistake in updating from a file pot inside the folder.

What do you think about it? This can be done for the whole plugins you have.
Thanks
Angelo

**Comment by htmgarcia** [comment]
I need to check due the structure of each plugin may be different.

**Comment by htmgarcia** [comment]
Already added this update through #1145

**Comment by wocmultimedia** [comment]
Hi @htmgarcia 
I reopened this issue just because I don't understand why the languages files have the same denominations but of course different string quantity in both Free and Pro version. Besides in my local free folder languages files .pot has 1205 strings and in the WP-systems only 445.
It would be nice understanding this language concept that I cannot figure out.
Thanks 
Angelo

**Comment by htmgarcia** [comment]
Hi @wocmultimedia

I use the same text-domain due development reasons. Almost all the code from free repository is included in the pro version. Using 2 text-domains is not possible due that very reason. I understand other PublishPress plugins uses 2 text-domains: one for free and one for pro, however that is possible for PP Blocks due the structure is different.

To generate the translation files for PP Blocks Pro I merge Free and Pro translations files (see links from the quote below) to generate the distribution translations for Pro version (the zip to install the plugin).

> Please ignore the final versions (like in your screenshot). That can lead to confusion. Only use the PO files from the Github repositories from master or main branch:
> 
>     * Free: https://github.com/publishpress/PublishPress-Blocks/tree/master/src/languages
> 
>     * Pro: https://github.com/publishpress/PublishPress-Blocks-Pro/tree/main/src/languages/source

I made sure those files are up-to-date in every new release, so you don't need to check anything else.

If you have more questions, please let me know.

**Comment by wocmultimedia** [comment]
Hi @htmgarcia 
I understand the difficulties introduced with the WP block system in all the fields. However, as I'm not very able to well use GitHub, can you tell me how to download the .po file from those links above mentioned?
So I can merge them with the previous version if needed and make the new translations.
Thanks a lot
Angelo

**Comment by htmgarcia** [comment]
The quick way is to download the whole repositories as zip each time a new release is available:
![Screen Shot 2023-01-25 at 11 27 23](https://user-images.githubusercontent.com/4999794/214637443-45bf4c21-2845-4807-aace-04bb6edcf98f.png)

You can download each PO file doing right click over "Raw" button > "Save as":
![Screen Shot 2023-01-25 at 11 26 24](https://user-images.githubusercontent.com/4999794/214637806-17543487-cb21-444c-9672-8b67453a4fca.png)

The recommended one is to [install a Github client](https://desktop.github.com/), "Open with Github desktop" (see screenshot below) to create a copy of the repository in your computer. Every time a new release is available, make sure to update your local copy.
![Screen Shot 2023-01-25 at 11 27 46](https://user-images.githubusercontent.com/4999794/214638314-1301ee2b-42d1-4448-9043-0829c0c08627.png)

**Comment by wocmultimedia** [comment]
Thanks a lot, I will try to do follow your instructions.

**Comment by htmgarcia** [comment]
I'm happy to help. Reopen this if needed.
