### ISSUE TITLE
Banner for block controls

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1165]
In free version to promote the Timezone Pro feature in Schedule

**Comment by htmgarcia** [comment]
@stevejburge proposal:
![Screen Shot 2023-02-09 at 10 45 01](https://user-images.githubusercontent.com/4999794/217881183-aa6a7469-b077-4c90-a927-6bdb136d6b8f.png)

**Comment by stevejburge** [comment]
@htmgarcia Sure, worth trying
