### ISSUE TITLE
Optimize "Some nested blocks are not loading its styles"

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#122]
Optimize the code for #117 

- [x] Recursive method to check nested blocks to replace the current manual check for each level (2 to 11)
- [x] Port methods for each block to load its own CSS for WP 5.4.2 and older
- [x] Load common CSS (required when nested blocks are added only)

**Comment by htmgarcia** [comment]
Missing "Recursive method to check nested blocks to replace the current manual check for each level (2 to 4)"
Code is incomplete:
```
$style_html .= $this->advgb_getNestedBlocksStyles($block); // This output is NOT correct!

/**
 * Recursive loop to find nested blocks and load their blocks's CSS and media files
 *
 * @since   2.4.4
 * @param   object  $block      Nested block
 * @param   string  $style_html CSS Styles
 * @param   integer $level      Nested block level
 * @return  string              CSS Styles
 */
public function advgb_getNestedBlocksStyles($block, $level = 2, $style_html = array()){

    if(isset($block['innerBlocks'])){
        foreach($block['innerBlocks'] as $key => $inner_block){

            // Get styles
            $new_style_html = $this->advgb_SetStylesForBlocks($inner_block['attrs'], $inner_block['blockName']);

            // Add the styles to the array
            array_push($style_html, $new_style_html);
            //echo str_repeat("--", $level) . $inner_block['blockName'] . ' [ ' . $level . ' ]<br>';

            self::advgb_getNestedBlocksStyles($inner_block, $level + 1);
        }
    }

    // Convert array to string
    $style_html = implode('', $style_html);

    //echo '<code>' . gettype($style_html) . '</code>'; // This output is correct!

    return $style_html;
}
```

**Comment by htmgarcia** [comment]
Now is on 11th level.

**Comment by htmgarcia** [comment]
@contactashish13 currently we use a manual nested blocks check to include media and CSS content [here](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/incl/advanced-gutenberg-main.php#L4719-L4797). 

We pretend to replace that code with this line:

`$style_html .= $this->advgb_getNestedBlocksStyles($block);`

that would call this method:

```
/**
 * Recursive loop to find nested blocks and load their blocks's CSS and media files
 *
 * @param   object  $block      Nested block
 * @param   string  $style_html CSS Styles
 * @param   integer $level      Nested block level
 * @return  string              CSS Styles
 */
public function advgb_getNestedBlocksStyles($block, $level = 2, $style_html = array()){

    if(isset($block['innerBlocks'])){
        foreach($block['innerBlocks'] as $key => $inner_block){

            // Get styles
            $new_style_html = $this->advgb_SetStylesForBlocks($inner_block['attrs'], $inner_block['blockName']);

            // Add the styles to the array
            array_push($style_html, $new_style_html);
            //echo str_repeat("--", $level) . $inner_block['blockName'] . ' [ ' . $level . ' ]<br>';

            self::advgb_getNestedBlocksStyles($inner_block, $level + 1);
        }
    }

    // Convert array to string
    $style_html = implode('', $style_html);

    //echo '<code>' . gettype($style_html) . '</code>'; // This output is correct!

    return $style_html;
}
```

however the output is not correct. Can you fix it?

**Comment by contactashish13** [comment]
@htmgarcia thanks for the brief explanation. Can you also mention the steps to reproduce this bug (+ the steps to reproduce a non-erroneous result... I see [here you mention it is at the 11th level, which means it must be correct before that level?](https://github.com/publishpress/PublishPress-Blocks/issues/122#issuecomment-812174434) )?

**Comment by htmgarcia** [comment]
@contactashish13 since "level" is not a term from Gutenberg, I need to clarify that to avoid any potential confusion:
<img width="972" alt="Screen Shot 2021-04-12 at 19 56 21" src="https://user-images.githubusercontent.com/4999794/114481065-6929a200-9bc9-11eb-965a-60910bd5f19d.png">

Note: this issue only affects blocks from our plugin in frontend.

In Gutenberg you can add blocks inside other blocks. Currently we load CSS styles for blocks from level 1st to 11th using an ugly approach that involves [repeating the same code from 2nd to 11th](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/incl/advanced-gutenberg-main.php#L4738-L4815), which is a bad coding practice. 

Users may have nested blocks in level 2nd, 3rd, 7th even 20th, just to mention possible scenarios. The idea is to dynamically load the CSS styles for all blocks no matter in which level are inserted. That is the purpose of `advgb_getNestedBlocksStyles()` method.

To reproduce a non-erroneous result, create nested blocks between level 1 and 11 and you won't see any issue in frontend. In the other hand, if you reach level 12th or beyond, things won't look good in frontend. Please test the example below to reproduce the issue.

### Admin

<img width="789" alt="Screen Shot 2021-04-12 at 19 33 14" src="https://user-images.githubusercontent.com/4999794/114479462-3500b200-9bc6-11eb-9df3-8999df931d3b.png">

### Frontend

The CSS generated from the block settings such as opacity doesn't load because simply are not included after level 11th. (Ignore the fact there is no image)
<img width="1005" alt="Screen Shot 2021-04-12 at 19 33 55" src="https://user-images.githubusercontent.com/4999794/114479478-3e8a1a00-9bc6-11eb-8fb4-5b1d117cec9b.png">

### HTML code

Paste this code through Code editor mode to reproduce the example above.

```
<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:advgb/image {"blockIDX":"advgb-img-8193a978-90bd-43a6-905d-daea9d4e84ad","changed":true} -->
<div class="wp-block-advgb-image advgb-image-block full-width advgb-img-8193a978-90bd-43a6-905d-daea9d4e84ad" style="background-image:url(undefined);height:500px;width:500px;justify-content:center;align-items:center"><a class="advgb-image-overlay" style="background-color:#000" target="_blank" rel="noopener noreferrer"></a><h4 class="advgb-image-title" style="color:#fff">Image title</h4><p class="advgb-image-subtitle" style="color:#fff">Your subtitle here</p></div>
<!-- /wp:advgb/image --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group -->
```

**Comment by contactashish13** [comment]
@htmgarcia thanks for that great explanation! Here is what I did to reproduce this at my end:

- created 2 posts - one with 9 levels and one with 17 levels
- without making any changes to the code viewed both on the front end. The one with 9 levels works but the one with 17 does not.
- used the recursive method exactly as [here](https://github.com/publishpress/PublishPress-Blocks/issues/122#issuecomment-812178768) without making any changes except adding an `error_log` line to output the level
- viewed both on the front end and **both** worked i.e. they both showed the style for the embedded block. Here is the output of the `error_log` for both

Your post said the return is not correct. Can you please clarify that?

### 9 levels
![image](https://user-images.githubusercontent.com/12953439/114502175-fc55ec80-9c48-11eb-9e23-8b83c2b10841.png)

```
level = 9
level = 8
level = 7
level = 6
level = 5
level = 4
level = 3
level = 2
```

### 17 levels
![image](https://user-images.githubusercontent.com/12953439/114502113-de888780-9c48-11eb-9228-fa91673a1c45.png)

```
level = 17
level = 16
level = 15
level = 14
level = 13
level = 12
level = 11
level = 10
level = 9
level = 8
level = 7
level = 6
level = 5
level = 4
level = 3
level = 2
```

### code changes
```
        public function contentPreRender($block)
        {
            // Search for needed blocks then add styles to it
            //$style = $this->addBlocksStyles($block);
			$style = $this->advgb_getNestedBlocksStyles($block);
            array_push($block['innerContent'], $style);

            return $block;
        }

		/**
		 * Recursive loop to find nested blocks and load their blocks's CSS and media files
		 *
		 * @param   object  $block      Nested block
		 * @param   string  $style_html CSS Styles
		 * @param   integer $level      Nested block level
		 * @return  string              CSS Styles
		 */
		public function advgb_getNestedBlocksStyles($block, $level = 2, $style_html = array()){

			if(isset($block['innerBlocks'])){
				foreach($block['innerBlocks'] as $key => $inner_block){

					// Get styles
					$new_style_html = $this->advgb_SetStylesForBlocks($inner_block['attrs'], $inner_block['blockName']);

					// Add the styles to the array
					array_push($style_html, $new_style_html);
					//echo str_repeat("--", $level) . $inner_block['blockName'] . ' [ ' . $level . ' ]<br>';

					self::advgb_getNestedBlocksStyles($inner_block, $level + 1);
				}
			}

			// Convert array to string
			$style_html = implode('', $style_html);

			error_log("level = $level");
			//echo '<code>' . gettype($style_html) . '</code>'; // This output is correct!

			return $style_html;
		}
```

**Comment by htmgarcia** [comment]
@contactashish13 while using `advgb_getNestedBlocksStyles()`, instead of Advanced Image, use an Advanced Button block. Change default color settings. Is more clear with that block. You can use this PR to test: https://github.com/publishpress/PublishPress-Blocks/tree/test-122

You'll notice styles for blocks are not working from any level, except for the 1st.

### Admin

<img width="388" alt="Screen Shot 2021-04-13 at 11 15 56" src="https://user-images.githubusercontent.com/4999794/114585950-c5340b00-9c49-11eb-9e4a-12f7c39dfd9f.png">

### Frontend

<img width="258" alt="Screen Shot 2021-04-13 at 11 16 01" src="https://user-images.githubusercontent.com/4999794/114585969-c8c79200-9c49-11eb-9693-92f33c114825.png">

> Your post said the return is not correct. Can you please clarify that?

The CSS stored in `$style_html` inside the method is correct:
```
// Convert array to string
$style_html = implode('', $style_html);
```

but is empty in the return: 
```
$style_html .= $this->advgb_getNestedBlocksStyles($block);
```

**Comment by htmgarcia** [comment]
Uncomment [this line](https://github.com/publishpress/PublishPress-Blocks/blob/test-122/src/incl/advanced-gutenberg-main.php#L4462) to echo the CSS that is expected to be returned [here](https://github.com/publishpress/PublishPress-Blocks/blob/test-122/src/incl/advanced-gutenberg-main.php#L4770).

**Comment by contactashish13** [comment]
@htmgarcia I've pushed my changes to https://github.com/publishpress/PublishPress-Blocks/pull/453 - it seems to work at any level now. Can you please check at your end too?

**Comment by htmgarcia** [comment]
Thanks @contactashish13! I got an error:
`Fatal error: Uncaught Error: [] operator not supported for strings in /wp-content/plugins/advanced-gutenberg/incl/advanced-gutenberg-main.php on line 4451`
It seems happening in pages with some blocks, like Accordions, Columns Manager

Please fix it and point the PR to develop branch.

**Comment by htmgarcia** [comment]
Accordions and Columns Manger have in common that both blocks are created with nested blocks.
As example: Columns Manager uses Columns block.
```
'advgb/columns'
--- 'advgb/column'
```

**Comment by contactashish13** [comment]
@htmgarcia fixed!
