### ISSUE TITLE
“Undefined index” PHP Warning Notice

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1263]
> Hi,
> 
> Your plugin is producing regular PHP warning notices as follows …
> 
> [31-Mar-2023 08:34:37 UTC] E_NOTICE: Undefined index: enable_columns_visual_guide in /wp-content/plugins/advanced-gutenberg/incl/advanced-gutenberg-main.php on line 2421
> 
> You have a warning notice
> Please can you add an isset() or other check to quieten this?
> 
> Many thanks,
> 
> Oliver

Original thread: https://wordpress.org/support/topic/undefined-index-php-warning-notice/

**Comment by htmgarcia** [comment]
> E_NOTICE: Undefined index: enable_columns_visual_guide in /wp-content/plugins/advanced-gutenberg/incl/advanced-gutenberg-main.php on line 2421

Fix through #1321

> [02-Apr-2023 10:23:58 UTC] E_NOTICE: Undefined variable: style_html in /wp-content/plugins/advanced-gutenberg/incl/advanced-gutenberg-main.php on line 4951

This seems to be a problem in 3.1.4.1 in advgb_AdvancedImageStyles() function. Was solved at some point in latest releases.
