### ISSUE TITLE
Inspect GitHub's Dependabot warnings or Pull Requests for relevant issues. Resolve any false positives first, then fix and commit the remaining issues.

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1330]

**Comment by htmgarcia** [comment]
Also include the ones from Pro https://github.com/publishpress/PublishPress-Blocks-Pro/security/dependabot

**Comment by andergmartins** [comment]
I fixed them for pro, except for one issue, but we can skip it for now. It is on dev requirements only.
