### ISSUE TITLE
WP 6.4 Compatibility

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1342]
Step to replicate:
1. Install WP 6.4 RC 2
2. Install PP blocks
3. Create new post

![image](https://github.com/publishpress/PublishPress-Blocks/assets/83811723/25222284-df9d-4904-9c61-d0f24267a525)

**Comment by htmgarcia** [comment]
It seems lodash was removed compeltely https://github.com/WordPress/gutenberg/pull/52571

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/919f853fd9ce1ba5da5eb2c5ef58c13e37ed6d2c
