### ISSUE TITLE
Blocks PRO Translation Updates_V3.2.2

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Blocks#1378]
Hi @andergmartins , @stevejburge ,

Here's copy of the files for Blocks PRO Translation Updates_V3.2.2
[publishpress-blocks-pro-3.2.2.zip](https://github.com/publishpress/PublishPress-Blocks/files/15306170/publishpress-blocks-pro-3.2.2.zip)

Thanks,
Angelo

**Comment by htmgarcia** [comment]
@wocmultimedia this seems to be the latest plugin installer. May you send only the updated language files, please?

**Comment by wocmultimedia** [comment]
Hi,
I apologize for the inconvenient. There was a mistake in adding the files. Here's the correct translations 
[BlocksPRO_TranslationUpdates_V3.2.2.zip](https://github.com/user-attachments/files/16274710/BlocksPRO_TranslationUpdates_V3.2.2.zip)
