### ISSUE TITLE
Count Up Pattern on WP 6.6

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Blocks#1389]
ISSUE: Gutenberg not responding

Step to replicate:
1. Add new page
2. Add Count Up block
3. Save that as pattern
4. Create new page
5. Add that pattern
6. Observe issue, it will only loading and the tab is not responding.

Only happens on WP 6.6.

**Comment by rizaardiyanto1412** [comment]
Happen with Content Display block as well

**Comment by rizaardiyanto1412** [comment]
Related: https://wordpress.org/support/topic/freezing-with-wordpress-6-6-update/

**Comment by htmgarcia** [comment]
Opened an issue in Gutenberg repository https://github.com/WordPress/gutenberg/issues/63909
