### ISSUE TITLE
In accordion, i would like to change Headings for H2 or H3 tags

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#139]
Customer request:

> In accordion, i would like to change Headings for H2 or H3 tags, but there is not an option.

**Comment by htmgarcia** [comment]
A new user requested this improvement: https://wordpress.org/support/topic/advanced-accordion-header/

**Comment by dlovere** [comment]
This is also a priority for me, since it does not allow for proper structuring of headings. I'm trying to get to 100% in SiteImprove :)

**Comment by htmgarcia** [comment]
@stevejburge @dlovere this has been covered in #80 and released in 2.8.0
