### ISSUE TITLE
debug log notice: undefined index: HTTP_REFERER

### ISSUE THREAD

**Issue by fargerio** [publishpress/PublishPress-Blocks#140]
running version 2.4.3 and I think most prior versions, a lot of these messages appear in the debug log:

```
[21-Aug-2020 07:14:31 UTC] PHP Notice:  Undefined index: HTTP_REFERER in /var/www/wordpress/wp-content/plugins/advanced-gutenberg/incl/advanced-gutenberg-main.php on line 1262
```

HTTP_REFERER is not always defined, this can easily be mitigated by replacing line 1262 with this:

```php
$referrer = '';
if(isset($_SERVER['HTTP_REFERER'])) {
    $referrer = $_SERVER['HTTP_REFERER'];
}
```
I did not find any guidelines on contributing, are you open to pull requests?

**Comment by fargerio** [comment]
Okay:
1. install wordpress
2. install the advanced-gutenberg plugin
3. add any advanced gutenberg block on a page
4. activate the debug.log in wp-config.php by setting `define('WP_DEBUG', true);`
5. visit the page with a browser that does not transmit the referer header or via a `<a href="" rel="noreferrer">` link.
6. find  `PHP Notice:  Undefined index: HTTP_REFERER` in debug.log


HTTP_REFERER is often not set, the [php documentation](https://www.php.net/manual/en/reserved.variables.server.php) even says:
> "In short, it cannot really be trusted."

**Comment by htmgarcia** [comment]
Thanks @fargerio!

I was unable to reproduce the issue, however we're aware of this and seems related to the login/register block. That being said I have an idea about a possible solution. Please replace [this method](https://github.com/publishpress/Advanced-Gutenberg/blob/master/src/incl/advanced-gutenberg-main.php#L1260-L1269) with the code below, and let me know if solved the issue:
```
public function handleLoginFailed()
{
    $from_advgb = isset($_POST['advgb_login_form']); // phpcs:ignore WordPress.Security.NonceVerification.Missing -- redirect
    if (!empty($_SERVER['HTTP_REFERER']) && $from_advgb) {
        $redirect = add_query_arg('login', 'failed', $_SERVER['HTTP_REFERER']);
        wp_safe_redirect($redirect);
        exit;
    }
}
```

**Comment by fargerio** [comment]
Yes, that also fixes it, anything that checks if `$_SERVER['HTTP_REFERER']` is set or not empty before using it works.

**Comment by tonydjukic** [comment]
Will this be included in the next update?
