### ISSUE TITLE
Custom CSS styles show really small text

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#149]
For some reason, the default styles mostly use tiny font sizes
https://publishpress.com/knowledge-base/default-css-styles/
![Screen Shot 2020-08-27 at 4 20 30 PM](https://user-images.githubusercontent.com/3868028/91490961-49837a80-e881-11ea-950c-53426f0b2b56.png)

**Comment by htmgarcia** [comment]
@stevejburge the font-size for these styles is 14px. The size may depends on the font-family which generally relies on the theme's CSS.

Using AG Theme, this is the result:
<img width="894" alt="Screen Shot 2020-10-14 at 13 01 39" src="https://user-images.githubusercontent.com/4999794/96027523-9c0efb00-0e1d-11eb-90a2-40ea299ee93f.png">

**Comment by htmgarcia** [comment]
This will apply to new installs only.
