### ISSUE TITLE
 In   "Advanced Button" block, the border style and width doesn't work

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Blocks#17]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Advanced Button" option
Step 5:   Change the border style and border width
Step 6:   Update and view post
 
Note:   Both, border style and width does not change
![image](https://user-images.githubusercontent.com/62157750/82886182-040a8680-9efb-11ea-960a-0e391c463f58.png)

**Comment by htmgarcia** [comment]
The border styles and width works fine.
