### ISSUE TITLE
Small translation issues in block settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#193]
![Screen Shot 2020-12-08 at 9 02 53 AM](https://user-images.githubusercontent.com/3868028/101493632-53af1d80-3934-11eb-969e-6591692923dd.png)

**Comment by stevejburge** [comment]
Some missing strings also in the styles area:

![Screen Shot 2020-12-08 at 9 04 43 AM](https://user-images.githubusercontent.com/3868028/101493741-75100980-3934-11eb-8fcd-d8d97c426368.png)

**Comment by stevejburge** [comment]
The blocks seem to be inconsistently translated:
![Screen Shot 2020-12-08 at 9 06 07 AM](https://user-images.githubusercontent.com/3868028/101493926-ac7eb600-3934-11eb-828e-9e8f028e16a7.png)

**Comment by htmgarcia** [comment]
@stevejburge the most complete translation is the Italian one. Please test that one.

**Comment by htmgarcia** [comment]
Good catch! This line doesn't have translation support.
<img width="342" alt="Screen Shot 2020-12-08 at 13 18 05" src="https://user-images.githubusercontent.com/4999794/101530716-e6ad7f00-3957-11eb-9e4b-729e26cc19ca.png">
