### ISSUE TITLE
List icons not showing correctly

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#202]
In the admin area:
<img width="1102" alt="Screen Shot 2020-12-18 at 10 56 29 AM" src="https://user-images.githubusercontent.com/3868028/102634381-c0d66600-411f-11eb-8907-1b838b808864.png">

On the frontend:
![Screen Shot 2020-12-18 at 10 57 04 AM](https://user-images.githubusercontent.com/3868028/102634397-c764dd80-411f-11eb-8e9a-5f8fadc90a16.png)

**Comment by stevejburge** [comment]
This seems to be an error with the margin and padding settings that hide part of the icon
<img width="261" alt="Screen Shot 2020-12-18 at 10 58 15 AM" src="https://user-images.githubusercontent.com/3868028/102634557-fed38a00-411f-11eb-8b61-6ce15d479a97.png">

**Comment by htmgarcia** [comment]
@stevejburge did a tweak to make the CSS have higher priority over the theme in use. 
Please refresh: https://demo.publishpress.com/advanced-list/
