### ISSUE TITLE
Can't change the title color for the Info Box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#204]
https://demo.publishpress.com/info-box/

In the admin area:
![Screen Shot 2020-12-18 at 1 22 55 PM](https://user-images.githubusercontent.com/3868028/102647684-29c7d900-4134-11eb-8706-e5c4340efb02.png)

On the frontend, the titles remain black:
<img width="954" alt="Screen Shot 2020-12-18 at 1 23 14 PM" src="https://user-images.githubusercontent.com/3868028/102647704-35b39b00-4134-11eb-916a-4729c47d8996.png">

**Comment by htmgarcia** [comment]
@stevejburge were the blocks duplicated? If that's the case, we have that issue with other blocks #112

**Comment by stevejburge** [comment]
@htmgarcia No, I don't think so. I was able to change the other settings. 

Just one or two CSS elements are being overriden by the theme, I think

**Comment by htmgarcia** [comment]
In a second check, I confirm is an issue on the theme that overrides the heading color.

Please clear cache and refresh: https://demo.publishpress.com/info-box/

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Theme/commit/2bc1c66eef8f1fb15fc3fdcb64da26a130d178ea

**Comment by stevejburge** [comment]
@htmgarcia Awesome, thanks
