### ISSUE TITLE
Slider is buggy in WooCommerce Products Blocks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#207]
https://demo.publishpress.com/woo-products/

You can see the dots are buggy - they can't be disabled

<img width="953" alt="Screen Shot 2020-12-18 at 4 11 40 PM" src="https://user-images.githubusercontent.com/3868028/102661967-dceffc80-414b-11eb-983f-270de4387903.png">

**Comment by htmgarcia** [comment]
@stevejburge we can improve the dots display. e.g. making some spacing which is an issue exclusive to our theme.
<img width="351" alt="Screen Shot 2020-12-21 at 14 52 15" src="https://user-images.githubusercontent.com/4999794/102821217-52520c00-439c-11eb-8bd5-eb50eaa39770.png">

https://github.com/publishpress/PublishPress-Theme/commit/6e96c9642914ed3ad0ed34ca92b84d0b743c5a91
https://github.com/publishpress/PublishPress-Theme/commit/78bc288198244e891868f0e85076002b2a782d69

**Comment by stevejburge** [comment]
Thanks @htmgarcia. Yes, got to make the demo look good 👍
