### ISSUE TITLE
custom_styles.css deletion triggers WordPress bug

### ISSUE THREAD

**Issue by Absotively** [publishpress/PublishPress-Blocks#213]
The custom_styles.css deletion in install.php can trigger [WordPress ticket #48689](https://core.trac.wordpress.org/ticket/48689). I'm not sure what conditions are needed to cause this aside from PublishPress Blocks being active.

Also, the warnings described there appear on the site even if WP_DEBUG is false. I suspect this means the custom_styles.css deletion code is being run before WP_DEBUG takes effect.

Making the deletion conditional on `$advgb_current_version`, in a similar manner to the other upgrade code in install.php, stops the warnings from appearing more than once. It doesn't fix the issue of the code running very early, though. I can submit a PR to add the condition if you like, but I don't know enough about plugin loading to suggest a more thorough fix.

**Comment by htmgarcia** [comment]
Hi @Absotively,
may we have the step by step details to reproduce the issue?

**Comment by Absotively** [comment]
I haven't managed to track down what it is about my site's setup that causes the warnings to appear even when WP_DEBUG is false.

To see the warnings when WP_DEBUG is true, remove write permissions from the wp_content directory for the webserver.

Now that I've looked into that, a third fix would probably be to pass the uploads directory to WP_Filesystem() as the context, since the webserver should have write permissions for the uploads directory even if it doesn't for the content directory.

**Comment by htmgarcia** [comment]
Thanks. We introduced the delete for custom_styles.css on September in [version 2.4.5](https://github.com/publishpress/PublishPress-Blocks/releases/tag/v2.4.5). Since this is our first report related, having a way to reproduce the possible issue is important for us.

This is happening in a regular WordPress site or in multiple sites installation?

**Comment by Absotively** [comment]
Regular WordPress site.

**Comment by htmgarcia** [comment]
Are you able to reproduce the issue in another site?

**Comment by Absotively** [comment]
I can reproduce on another site if I set the wp_content permissions as I described and turn on WP_DEBUG.

I have not yet been able to reproduce the warnings appearing when WP_DEBUG is false on another site.

**Comment by htmgarcia** [comment]
We use `WP_Filesystem()` to delete the file when exists - https://github.com/publishpress/PublishPress-Blocks/blob/master/src/install.php#L135-L144
