### ISSUE TITLE
"Space between columns" can push content off the page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#214]
Using PublishPress Blocks and the Columns Manager block, choose "Space between columns"

<img width="1380" alt="Screen Shot 2021-01-06 at 10 50 42 AM" src="https://user-images.githubusercontent.com/3868028/103788650-17dba680-500d-11eb-84cf-1c6b1ffd6947.png">

If you do this, it can push your content off the right-side of the page:

![Screen Shot 2021-01-06 at 10 51 25 AM](https://user-images.githubusercontent.com/3868028/103788715-2a55e000-500d-11eb-911e-2cf118fee391.png)

**Comment by htmgarcia** [comment]
@stevejburge I noticed that yesterday but I'm not sure if is an issue with Columns Mange block or the theme. regular Columns blocks doesn't have this problem.

**Comment by htmgarcia** [comment]
This issue happens in other themes  well, so I assume is a bug. The screenshot below comes from Twenty Twenty-One theme:
<img width="1375" alt="Screen Shot 2021-01-07 at 11 27 23" src="https://user-images.githubusercontent.com/4999794/103924329-7cfdcd80-50db-11eb-8f06-771f2593a7ac.png">

**Comment by htmgarcia** [comment]
The spacing between columns for 4 and 6 columns when selecting the grid style in tablet and/or mobile is missing. Probably something to tackle in a separate issue.
<img width="261" alt="Screen Shot 2021-01-08 at 14 27 20" src="https://user-images.githubusercontent.com/4999794/104061145-a5f68f00-51bd-11eb-8f4d-15d40178c758.png">

<img width="646" alt="Screen Shot 2021-01-08 at 14 24 30" src="https://user-images.githubusercontent.com/4999794/104061089-8cedde00-51bd-11eb-88ea-bbc7923f1d94.png">

**Comment by htmgarcia** [comment]
Same case with 6 columns when displaying 3 columns per row:
<img width="276" alt="Screen Shot 2021-01-08 at 14 29 12" src="https://user-images.githubusercontent.com/4999794/104061385-13a2bb00-51be-11eb-87f0-210d37af1026.png">

**Comment by htmgarcia** [comment]
@stevejburge at this point, the main issue is fixed.  Below I share a screenshot for comparison between core columns block and columns manager:
<img width="1396" alt="Screen Shot 2021-01-08 at 14 34 19" src="https://user-images.githubusercontent.com/4999794/104061695-b0fdef00-51be-11eb-983b-cd8517db8302.png">

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks/commit/9e879a76fdf888ea7f756182246066b43aa32acf
