### ISSUE TITLE
Add some style to Summary block

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#218]

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks/commit/8ca4c41ca80ee7184b511f819d22ba649af55f91
https://github.com/publishpress/PublishPress-Blocks/commit/766bdce631e01541d3e28c1081ade4e17f0fc225

**Comment by htmgarcia** [comment]
@stevejburge I see dynamic code that generates margin-left based on heading level, however I'm not able to figure out why this is necessary. Do we have by chance a more complex Summary block result to analyze (like one with 2 or 3 levels)?

**Comment by htmgarcia** [comment]
Oh, I think I got it:
<img width="323" alt="Screen Shot 2021-01-12 at 21 29 13" src="https://user-images.githubusercontent.com/4999794/104403014-3c5be500-551d-11eb-884e-dae6198a3e67.png">

An h2 heading will become parent of h3 headings and so on.

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks/commit/d4662ccbcec799264b9047c719e6d3acad614e32
https://github.com/publishpress/PublishPress-Blocks/commit/846d2b418482c5253da85ddcbc706be03b43b7e6
https://github.com/publishpress/PublishPress-Blocks/commit/40dc2660ad5ce8b5cbf4993102e48221a0bf4a10

**Comment by stevejburge** [comment]
Awesome, thanks @htmgarcia
