### ISSUE TITLE
Audio Block: Autoplay feature doesn't work after it's switched on

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#226]
1. Go to WP Admin Dashboard
2. Go to Pages menu
3. Click Page that has an Audio block in it
4. Click the Audio block. The Audio settings will appear on the right side of the page
5. Switch on the Autoplay button
6. Click Update button on the top-right of the page
7. "Page Updated" notification will appear on the bottom left. Click View Page link
Result: Audio won't play automatically. 

Note: Audio will still play automatically if we set up the audio setting to Autoplay mode since the beginning of page/post creation. If we change to autoplay from manual play after page/post is created, it won't work.

Please see the attachment [here](https://drive.google.com/file/d/1LSZHgkzZia4ekp9Uw9qXGShmlHIOZp7b/view?usp=sharing)

**Comment by htmgarcia** [comment]
Hi @fitrir,
please note Audio is a core block. In addition it seems your site is not up-to-date. Update to WP 5.6 and if the issue persists, install and activate Gutenberg plugin to get any fix before WP core include them in the core.
