### ISSUE TITLE
Cover Block: Vertically centered content inside Cover Block has extra bottom-padding

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#227]
1. Go to WP Admin Dashboard
2. Go to Pages menu
3. Click Add New button
4. Type "Lorem Page" on Add title section
5. Click "+" button to add new block
6. Type "Cover" on the search bar
7. Choose Black color
8. Type "Lorem Ipsum"
9. Click Publish button on the top right of the page
10. Click View Page button
Result: The text inside the Cover Block has extra bottom padding, thus it's not vertically centered

![page-editor-cover-text-vertical-center](https://user-images.githubusercontent.com/36120286/105284107-9d5f6a80-5b66-11eb-91da-b21794f08031.png)
![actual-cover-extra-bottom-padding](https://user-images.githubusercontent.com/36120286/105284117-a05a5b00-5b66-11eb-9971-04a9e3934f84.png)

**Comment by htmgarcia** [comment]
Hi @fitrir,
I'm afraid is the same case as #226 - Please follow the same advice. 

To report bugs from core blocks, [Gutenberg repository](https://github.com/WordPress/gutenberg) is the right place.
