### ISSUE TITLE
Advanced Button: Wide width option doesn't change the button size and pushes the button far to the left of the page

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#236]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced button" on the search bar then click "Advanced Button" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Click "Change Alignment" button represents by 3 horizontal lines icon
7. Click "Wide Width"
8. Update the page by clicking "Update" button on the top right side

Result:  No size difference of the button between "Wide width mode" and the regular one, and the button position is pushed far to the left.

![advanced_button_left_align](https://user-images.githubusercontent.com/36120286/105813808-40e4bc80-5f65-11eb-9e42-90031d00f55d.png)
![advanced_button_wide_width](https://user-images.githubusercontent.com/36120286/105813816-43dfad00-5f65-11eb-97aa-cfeb954db52e.png)

**Comment by htmgarcia** [comment]
Thanks @fitrir! Seems connected to #237

**Comment by htmgarcia** [comment]
We removed this on #237
