### ISSUE TITLE
Advanced Button: Full width option doesn't change the size of the button width

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#237]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced button" on the search bar then click "Advanced Button" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Click "Change Alignment" button represents by 3 horizontal lines icon
7. Click "Full Width" option
8. Update the page by clicking "Update" button on the top right side of the page

Result: The width of the button doesn't change and it's pushed to the left corner of the page

![advanced_button_left_align](https://user-images.githubusercontent.com/36120286/105814856-dfbde880-5f66-11eb-9a84-db6475adce37.png)
![advanced_button_full_width](https://user-images.githubusercontent.com/36120286/105814875-e51b3300-5f66-11eb-8571-724493fa544f.png)

**Comment by htmgarcia** [comment]
Thanks @fitrir! I confirm the issue.
