### ISSUE TITLE
Advanced Table: Left and Right Alignments don't work on Twenty Twenty theme

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#242]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced table" on the search bar then click "Advanced Table" block
5. Leave Column Count and Row Count as is
6. Click "Create" button. New Table block will be created on the Page Editor screen with its editing panel
7. Fill out the table
8. Click "Change Alignment" button represents by 3 horizontal lines icon on the editing panel
9. Click "Align left"
10. Update the page by clicking "Update" button on the top right side of the page
11. Click "Align right"
12.  Update the page by clicking "Update" button on the top right side of the page

Result: "Align Left" will push the table to the far left and "Align Right" will push the table to the far right. Table width will be changed as well.

![advanced-table-align-left-2020](https://user-images.githubusercontent.com/36120286/106345670-bce14c00-6266-11eb-9c13-a48ec5813b32.png)

![advanced-table-align-right-2020](https://user-images.githubusercontent.com/36120286/106345671-bd79e280-6266-11eb-9c89-bfb9ba973c37.png)

**Comment by htmgarcia** [comment]
Thanks @fitrir ! Technically the table is floating to left/right instead of being aligned.

**Comment by htmgarcia** [comment]
By using center or default alignment the problem is solved. Due the CSS from the theme is not possible a solution without causing bugs while using other themes different to the core.
