### ISSUE TITLE
Advanced Table: Full width table length with "Wide Width" option on Twenty Twenty-One theme

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#243]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced table" on the search bar then click "Advanced Table" block
5. Leave Column Count and Row Count as is
6. Click "Create" button. New Table block will be created on the Page Editor screen with its editing panel
7. Fill out the table
8. Click "Change Alignment" button represents by 3 horizontal lines icon on the editing panel
9. Click "Wide width"
10. Update the page by clicking "Update" button on the top right side of the page

Result: Table will have full-width length on Twenty Twenty-One theme

![advanced-table-wide-width_2020](https://user-images.githubusercontent.com/36120286/106346165-e8b20100-6269-11eb-93d9-a03862299286.png)

![advanced-table-wide-width_2021](https://user-images.githubusercontent.com/36120286/106346166-e94a9780-6269-11eb-8e02-2d14d09a60c0.png)

**Comment by htmgarcia** [comment]
@fitrir wide and full width are generating the same result. Worth to consider to use concise alignment settings. Results can differ from theme to theme.
