### ISSUE TITLE
Advanced Tab: Additional overlay color for Active tab on Twenty Twenty-One theme

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#244]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced tab" the search bar then click "Advanced Tabs" block. 
5. New Tabs block will be created on the Page Editor screen with its editing panel
6. Fill out the tab title and its content
7. Update the page by clicking "Update" button on the top right side of the page

Result: Active tab will have light color overlay on Twenty Twenty-One theme regardless of the active background color we choose.

![advanced-tab-active_2020](https://user-images.githubusercontent.com/36120286/106346956-76dcb600-626f-11eb-91d4-f0fb5bef4f47.png)

![advanced-tab-active_2021](https://user-images.githubusercontent.com/36120286/106346957-77754c80-626f-11eb-8c04-5867de018e57.png)

**Comment by htmgarcia** [comment]
@fitrir sorry, I wasn't able to reproduce in my end. The color background for active tab works fine in my end.
