### ISSUE TITLE
Sentiment_neutral icon under sharp style has no display.  

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#245]
Steps to Reproduce : 
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced Icon" on the search bar then click "Advanced Icon" block
5. New Icon block will appear on the Page Editor screen with its editing panel
6. Click Icon 1 Settings and Click "Icon Selection" from editing panel 
7. Click the drop down list of style and choose "Sharp". 
8. Click Search bar and write "Sentiment_neutral" 9.
9. Only name appears. 

Actual Result:  Their is no Sentiment_neutral logo to display on icon search list.
![sharpsentimentneutral](https://user-images.githubusercontent.com/76508916/106395362-c7126000-63b6-11eb-9013-3bbc75de9ce7.PNG)
![icon-sentimental_neutral](https://user-images.githubusercontent.com/76508916/106395398-f032f080-63b6-11eb-9c82-0874a0feef9a.png)

**Comment by htmgarcia** [comment]
Thanks @rishavarora ! Probably an update on the font files is required.
