### ISSUE TITLE
"Sentiment_neutral" Icon under style sharp not displayed.

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#246]
Steps to Reproduce :

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced Icon" on the search bar then click "Advanced Icon" block
5. New Icon block will appear on the Page Editor screen with its editing panel
6. Click "Icon 1 Settings" and then Click "Icon Selection" from editing panel
7. Click the arrow- drop down list of style and choose "Sharp"
8. Click Search bar and write "Sentiment_neutral" 
9. Click on the Icon  "Sentiment_neutral"  and press Apply.

Actual Result: The Logo is not displayed. 
![icon-senti-no display](https://user-images.githubusercontent.com/76508916/106397280-650b2800-63c1-11eb-9dc4-e6819619b32d.PNG)

**Comment by htmgarcia** [comment]
@rishavarora duplicated from #245
