### ISSUE TITLE
Style Drop Down Arrow is not functional. 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#247]
Steps to Reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced Icon" on the search bar then click "Advanced Icon" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Click "Icon 1 Setting" button 
7. Edit Icon settings appears 
8. Click "Icon Selection"
9. New Window opens with Icon List
10. Click style drop down arrow .
11. 
Expected Result:  When Drop Down arrow is clicked, list of Style with six options opens.
Actual Result: When Drop down arrow button is clicked. It does not open. 
![ddl](https://user-images.githubusercontent.com/76508916/106398378-4445d100-63c7-11eb-8a4f-439f518a4ed6.PNG)

**Comment by htmgarcia** [comment]
@rishavarora works fine in my end. Please check again and re-open this issue if required.
