### ISSUE TITLE
Inline Image previewed in new tab is not displayed

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#249]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced Image" on the search bar then click "Advanced Image" block
5. Image window appears on the Page and New Button block will appear on the Page Editor screen with its editing panel
6. Click "Open Media" button 
7. Select the media from saved file or upload.
8. Upload image -> choose from saved drive and click upload.
9.  After Image is uploaded to the page, Click the floating bar on the top of uploaded image.
10. Click down-arrow next to link. 
11. From the List choose "Inline Image ".
12. New window appears with title "Select the media" 
12. Select the media from saved file or upload. 
13. Click "Update" on the top left.
14. Click "Preview" and choose "Preview in new tab"
![inlineimage](https://user-images.githubusercontent.com/76508916/106564806-962f4980-64e2-11eb-98b3-65dd421d15a9.PNG)
![inlineimagepart2](https://user-images.githubusercontent.com/76508916/106564809-96c7e000-64e2-11eb-97ad-a1b8b7bd9789.PNG)

**Comment by htmgarcia** [comment]
Thanks @rishavarora ! Inline images are not expected to be displayed here. Opened an issue #263
