### ISSUE TITLE
Advanced Accordion title post is not fully displayed on Mobile Preview 

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#252]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. New post page will be displayed
5. Type "Advanced Accordion" on the search bar and click "Advanced Accordion" block
6. “Add title” and 2x Header text will be displayed 
7. Add title as “(Test) Advanced Accordion”
8. Click on Preview top right corner and select “Mobile” from drop menu

Expected results: Title displayed properly on mobile 
Actual results: Title does not display fully as the example above "(Test) Advanced Accordion", Accordion is not there on the preview.

(Screenshot attached)

![Mobile Preview - Advanced Accordion](https://user-images.githubusercontent.com/78010011/106836874-cdbb0480-664e-11eb-9dd5-3cac65bc744e.PNG)

**Comment by htmgarcia** [comment]
Thanks @Ahmedabbas21! This seems related to the editor, not PublishPress Blocks.
