### ISSUE TITLE
Cannot seem to have more options for order list icons to select from. 

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#253]
Steps to Reproduce

1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. New post page will be displayed
5. Type "Advanced Accordion" on the search bar and click "Advanced Accordion" block
6. “Add title” and 2x Header text will be displayed 
7. Add title as “Full List of Mercedes-AMG Cars Ever Made”
8. Click “Order list” and select options are only numbers or circle dot icons

Expected results: More options to select from such as “stars, underscore, right-side arrow, etc”
Actual results: There are only two options to choose from only numbers or black-circle shapes

![Order list color - Advanced Accordion](https://user-images.githubusercontent.com/78010011/106846666-2647cd00-6662-11eb-81ca-94ccce7fdab9.PNG)

**Comment by htmgarcia** [comment]
The List block belongs to the core. Doesn't have many options like Advanced List block.
