### ISSUE TITLE
Color options to select from for order list icons instead of installing another plugin

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#254]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. New post page will be displayed
5. Type "Advanced Accordion" on the search bar and click "Advanced Accordion" block
6. “Add title” and 2x Header text will be displayed 
7. Add title as “Full List of Mercedes-AMG Cars Ever Made”
8. Click “Order list” and select "Color text": display only color to text not to the order list icons

Expected results: Color options for order list icons that can match the text 
Actual results: No color options to choose from for order list icons

![Order list color - Advanced Accordion](https://user-images.githubusercontent.com/78010011/106847051-04027f00-6663-11eb-9520-da15c7a556b0.PNG)

**Comment by htmgarcia** [comment]
I wasn't able to reproduce this issue. Color options are available in my end.
<img width="1237" alt="Screen Shot 2021-02-05 at 18 14 28" src="https://user-images.githubusercontent.com/4999794/107101794-1654f800-67de-11eb-9884-9fdff1520ba5.png">
