### ISSUE TITLE
Image Slider does not display images when Enabling RTL 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#266]
Steps to Reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Image Slider " on the search bar then click "Image Slider" block
5. Click "Add Images" 
6. Choose five images from Media gallery or Upload New images and Click Select
7.  On the side editor Enable RTL.
8. Click Update and choose Preview in new Tab 

Expected Result: Uploaded images can be slided from Right to Left.  
Actual Result: Uploaded images has no display.
![displayin2](https://user-images.githubusercontent.com/76508916/107108348-10feaa00-67ec-11eb-9c66-dcdcfe94473e.PNG)
![nodisplay](https://user-images.githubusercontent.com/76508916/107108350-11974080-67ec-11eb-9f47-946119865bcd.PNG)

**Comment by htmgarcia** [comment]
Duplicated #268
