### ISSUE TITLE
Images Slider: Images don't appear when RTL is enabled

### ISSUE THREAD

**Issue by fitrir** [publishpress/PublishPress-Blocks#268]
1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Images slider" the search bar then click "Images slider" block
5. Click "Add Images" button
6. "Media Window" will appear. Select any 4 pictures from Media Library
7. Click "Select" button on the bottom left of the screen. New Image Slider block will be created.
8. Switch on "Enable RTL" button on the Image Setting located on the right side of the screen
9. Update the page by clicking "Update" button on the top right side of the page

Result: Images will not appear on the Images Slider block when RTL is enabled

![images_slider_rtl_on](https://user-images.githubusercontent.com/36120286/107172937-792fc600-697b-11eb-898e-78ae9d1c64bb.png)

![images_slider_rtl_off](https://user-images.githubusercontent.com/36120286/107172949-7fbe3d80-697b-11eb-9ebb-2fd8012ea0a8.png)

**Comment by htmgarcia** [comment]
Thanks @fitrir. I confirm the bug.

**Comment by htmgarcia** [comment]
@stevejburge RTL seems completely buggy. Since there is an text alignment to right option, we can get rid of RTL.
