### ISSUE TITLE
Highlighted login form Username when changes to bold Shows HTML Code.

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#272]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to  Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Username or Email" on login form 
7. Click Bold(B) from floating Editor Tool 
8. Click "Update"
9. Click "Preview in new tab"

Expected Result: When "Username or Email" is highlighted, bold is selected, Username font changes to Bold letters. 

Actual Result: When "Username or Email" is highlighted, bold is selected, username font does not change to Bold Letters.
![username](https://user-images.githubusercontent.com/76508916/107602940-112de980-6be0-11eb-8e9d-edd5a3a2c7a4.PNG) 
![loginusername](https://user-images.githubusercontent.com/76508916/107602938-10955300-6be0-11eb-9af3-1d3f43e2ab2a.PNG)

**Comment by htmgarcia** [comment]
Fixed with #347
