### ISSUE TITLE
Highlighted Password keyword in login form  when changes to bold shows HTML Code

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#273]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Password" on login form
7. Click Bold from floating Editor Tool 
8. Click "Update"
9. Click "Preview in new tab"

Expected Result: When "Password" is highlighted, bold is selected, password font changed to Bold letters. 
![passwordlogin](https://user-images.githubusercontent.com/76508916/107605081-fc088900-6be6-11eb-9e3a-dc96de6fcd03.PNG)
![passwordlogin1](https://user-images.githubusercontent.com/76508916/107605083-fca11f80-6be6-11eb-93a4-2bf1589e671e.PNG)

Actual Result: When "Password" is highlighted and bold is selected, password font does not change to Bold Letters.

**Comment by htmgarcia** [comment]
Fixed with #347
