### ISSUE TITLE
Changes to Text color "remember me"  show changes on keyword password.

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#274]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Remember me" on login form
7. Click Text color from floating Editor Tool 
8. Click "Update"
9. Click "Preview in new tab"

Expected Result: When keyword "Remember me " is highlighted, keyword color is changed

Actual Result: When keyword "Remember me" is highlighted, it select and changes color of keyword "Password" 

![remeberme](https://user-images.githubusercontent.com/76508916/107607026-ccf51600-6bec-11eb-9bde-ed9e41407bc9.PNG)
![rememberme1](https://user-images.githubusercontent.com/76508916/107607027-cd8dac80-6bec-11eb-843f-e0faee6aa693.PNG)

**Comment by htmgarcia** [comment]
Fixed with #347
