### ISSUE TITLE
Keyword "Username or Email" Text color change shows HTML Code Tag

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#283]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Username or Email" on login form
7. Click down arrow list from floating Editor Tool 
8. Choose Text Color from drop down list.
9. Choose any color other the default. In this case Green is selected. 
10. Click "Update"
11. Click "Preview in new tab"

Expected Result: When default Text Color of Keyword "Username or Email" is changed to other color, Keyword color is changed.     

Actual Result: When default Text Color of Keyword "Username or Email" is changed to other color, keyword color is not changed and HTML code tag appeared. 

![usernamecolor2](https://user-images.githubusercontent.com/76508916/108023774-28057f00-6fd8-11eb-9003-8c580d0ef2b1.PNG)
![usernamecolor1](https://user-images.githubusercontent.com/76508916/108023773-276ce880-6fd8-11eb-900a-4e3923245651.PNG)

**Comment by htmgarcia** [comment]
Fixed with #347
