### ISSUE TITLE
 Keyword "Don't have an account?" Text color change shows HTML Code Tag

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#288]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Don't have an account?" on login form
7. Click down arrow list from floating Editor Tool 
8. Choose Text Color from drop down list.
9. Choose any color other the default. In this case purple is selected. 
10. Click "Update"
11. Click "Preview in new tab"

Expected Result: When default Text Color of Keyword "Don't have an account?" is changed to other color, Keyword color is changed.     

Actual Result: When default Text Color of Keyword "Don't have an account?" is changed to other color, keyword color is not changed and HTML code tag appeared. 

![DONTHAVE1](https://user-images.githubusercontent.com/76508916/108157275-32d31900-7097-11eb-92c0-2ed1083e31ed.PNG)
![DONTHAVE2](https://user-images.githubusercontent.com/76508916/108157277-336baf80-7097-11eb-9df2-0a3d4e0335b1.PNG)

**Comment by htmgarcia** [comment]
Fixed with #347
