### ISSUE TITLE
Keyword "Register now" Text color change shows HTML Code Tag

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#289]
Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Login/Register Form" on the search bar then click "Login/Register Form" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Highlight keyword "Register now" on login form
7. Click down arrow list from floating Editor Tool 
8. Choose Text Color from drop down list.
9. Choose any color other the default. In this case orange is selected. 
10. Click "Update"
11. Click "Preview in new tab"

Expected Result: When default Text Color of Keyword "Register now" is changed to other color, Keyword color is changed.     

Actual Result: When default Text Color of Keyword "Register now" is changed to other color, keyword color is not changed and HTML code tag appeared. 

![register1](https://user-images.githubusercontent.com/76508916/108159790-99a70100-709c-11eb-9fcd-81bcdbf27562.PNG)
![register2](https://user-images.githubusercontent.com/76508916/108159791-9ad82e00-709c-11eb-9d89-6ffe7fedfa26.PNG)

**Comment by htmgarcia** [comment]
Thanks @rishavarora! Fixed.
