### ISSUE TITLE
2x "Time icons" displayed that are identical (duplicated) 

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#291]
Steps to Reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. Type "Advanced Icons" on the search bar and click "Advanced Icons" block
5. Add title as “(Test) Advanced Icon” and Select “Icon” that was added
6. On right top corner, Click “Settings” icon, block settings bar will display on right side
7. Click on “Icon 1 Settings” and Click on “Icon Selection”, list of icons will be displayed
8. On that icons list, there are 2 duplicated “time icon” (see screenshot)

Expected results: Only 1 icon displays unless is designed as Requirements Specification 
Actual results: 2x time icons displayed (second screenshot)

Screenshot #1 
![time icon duplicated](https://user-images.githubusercontent.com/78010011/108583857-6ad59880-72f1-11eb-9f20-e14431db0630.PNG)

**Comment by htmgarcia** [comment]
Thanks @Ahmedabbas21 ! 

The icon seems duplicated however the names are in singular and plural. Is an odd scenario but technically is not a bug.
