### ISSUE TITLE
Desktop preview is not the same as live site when Icons added

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#292]
Steps to Reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. Type "Advanced Icons" on the search bar and click "Advanced Icons" block
5. Add title as “(Test) Advanced Icon” and Select “Icon” and add 5 icons
6. Click "preview" and select desktop view, all 5 icons will be display horizontally (see screenshot 1)

Expected results: Live site displays view same as the preview 
Actual results: View site live, 4 icons diplayed horizontally and 1 icon under them (see screenshot 2)

Note: (Using Twenty Twenty-One theme)

Screenshot 1

![Icons Desktop view](https://user-images.githubusercontent.com/78010011/108584246-973ee400-72f4-11eb-8cfd-f87f84254454.PNG)

Screenshot 2

![Site view of icons](https://user-images.githubusercontent.com/78010011/108584250-a756c380-72f4-11eb-8625-173a28094885.PNG)

**Comment by htmgarcia** [comment]
Hi @Ahmedabbas21,
try previewing with a different theme.
