### ISSUE TITLE
Newsletter block does not show warning when Email format is not followed.

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#325]
Steps to Reproduce 

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Newsletter" on the search bar then click "Newsletter" block
5. New Newsletter block will appear on the Page Editor screen with its editing panel on the side
6. Click "Form Settings" button and choose Style to Alternate
7. Newsletter block now has "First Name", "Last Name" and "Email"
8. Enter First Name-" King" , Last Name=" Prussia" and Email- King@prussia. 
9. Click Submit. 

Expected Result: When Email is entered without domain name, an Error message Appears. 
Actual Result:  When Email is entered without domain name, Information is processed, submit successful message appears.

![NEWSLETTER](https://user-images.githubusercontent.com/76508916/109365011-fb0d6380-7844-11eb-8363-91f6263702ac.PNG)

**Comment by htmgarcia** [comment]
Thanks @rishavarora! I was able to reproduce using `King@prussia.` (with dot at the end). The broken email address is not even saved according to the CSV export from admin.
