### ISSUE TITLE
In "Count Up" block, there are some option missing to customize the text

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Blocks#33]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Count Up" option
Step 5:   Add a count up number and a description and a header text
 
Note:   There are options missing to further customize text for "Header", "Count Up" and "Description", like: size for "Header" and "Description", alignment, lower case for "Header" text.
![image](https://user-images.githubusercontent.com/62157750/83813703-bddbc280-a672-11ea-9007-97710e4fb6bf.png)

**Comment by htmgarcia** [comment]
We're skipping lowercase setting due the user can simply type the text in that format.
