### ISSUE TITLE
Image size on live site does not match on Desktop preview

### ISSUE THREAD

**Issue by Ahmedabbas21** [publishpress/PublishPress-Blocks#337]
Steps to Reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit.
3. Click "+/plus" sign to add a new PublishPress block.
4. Type "Advanced Image" on the search bar and click "Advanced Image" block
5. Add title as “(Test) Advanced Image” and Add “Image” from Media Library 
6. On right top corner, click “Settings” icon, block settings bar will display on right side.
7. Add “Title & Subtitle” and select “Text Alignment”, Select “Top & Left” for Vertical & Horizontal  
8. Click on “Preview” and Select “Desktop” option (Screenshot #1)
9. Go to the live site and view the post from “desktop”. (Screenshot #2)
Expected results: “Live site” matches preview as “Preview” unless is designed as Requirements Specification (Screenshot Attached)
Actual results: “Live site” of image size does not match “Desktop preview” (Screenshot Attached)

Screenshot #1 
![Title   sub space on desktop preview](https://user-images.githubusercontent.com/78010011/110282122-c9a63d80-7f92-11eb-96d7-56e6ee4fe5b5.PNG)

Screenshot #2 
![Title   sub space is different on live](https://user-images.githubusercontent.com/78010011/110282154-d75bc300-7f92-11eb-8d16-b274ddb3d0ab.PNG)

**Comment by htmgarcia** [comment]
Thanks @Ahmedabbas21! It seems the theme is cropping the result. Testing with "Twenty Twenty-One" theme I see a similar behavior which depends on the available width in frontend and edit screen. Not an issue.
