### ISSUE TITLE
Single Line Description alignment is aligned properly

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#349]
Steps to Reproduce: 

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Testimonial" on the search bar then click "Testimonial" block
5. New Testimonial block will appear on the Page Editor screen with its editing panel
6. Enter Atleast  three profile  such that "Person Name", "Position " and "Description-one line"
7. Turn "Center Mode" to right.
7. Update the page by clicking "Update" button on the top right side
8.  Preview in new tab

Expected Result: All Three Profile added are aligned properly and can be scrolled using dots. 
Actual Result: All Three profile added are not aligned properly, one can see other profile. 
![testimonialcenter](https://user-images.githubusercontent.com/76508916/110901486-3e41ea80-82b9-11eb-8731-cffbd8d6cea0.PNG)

**Comment by htmgarcia** [comment]
Thanks @rishavarora! If I follow you, text from another testimonial is visible, correct?
<img width="932" alt="Screen Shot 2021-03-12 at 18 09 51" src="https://user-images.githubusercontent.com/4999794/111011190-3be59c00-835e-11eb-81c9-b981da571d5c.png">

**Comment by rishavarora** [comment]
Yes.

**Comment by htmgarcia** [comment]
This is solved by disabling center mode. By rethinking, I don't consider this as issue.
