### ISSUE TITLE
Simplify submenus

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#35]
I'm not sure we need slidedown menus here?

"Configuration" and "Default blocks config" can be top-level, maybe with these names:

- "Settings"
- "Default Block Settings"

<img width="308" alt="Screen Shot 2020-06-05 at 3 32 14 PM" src="https://user-images.githubusercontent.com/3868028/83915770-e4b4fa00-a741-11ea-8904-02c6a58ab11c.png">

**Comment by htmgarcia** [comment]
@stevejburge proposal:
<img width="296" alt="Screen Shot 2021-02-23 at 18 25 33" src="https://user-images.githubusercontent.com/4999794/108926720-94016c00-7604-11eb-9a00-5141dd08d69a.png">
