### ISSUE TITLE
Testimonial Text color changed from floating bar cannot be overdone by Editing panel Text color 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#350]
Steps to Reproduce: 

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Testimonial" on the search bar then click "Testimonial" block
5. New Testimonial block will appear on the Page Editor screen with its editing panel
6. Enter Atleast  three profile  such that "Person Name", "Position " and "Description"
7. Highlight the text " Person Name" "Description" and "Position"
8. Click downward arrow from Floating bar Menu and Choose Text color
9. Choose Personal name to Red color , Position to "Pink Color and Description to Black color
10. Highlight the text " Person Name" "Description" and "Position"
11. Choose Text Color from  Editing panel for Personal name, position and Description to different colors
12. Update the page by clicking "Update" button on the top right side
13.  Preview in new tab.

Expected Result:  Testimonial text colors are changed using floating bar and then those text colors are changed using Editing panel , colors changed. 
Actual Result: Testimonial text colors are changed using floating bar and then those text colors are changed using Editing panel , colors does not change to new colors. 

![testimonal](https://user-images.githubusercontent.com/76508916/110908910-52d7b000-82c4-11eb-8723-65cd16bc7804.PNG)

**Comment by htmgarcia** [comment]
The Text color setting from the toolbar shouldn't available. The colors are defined on the right sidebar.
