### ISSUE TITLE
Summary block does not update changes made to headings. 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#351]
Steps to Reproduce:

1. Install and Activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress Block
4. Type "Summary" on the search bar then click "Summary" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Click Heading "Acute Myeloid Leukemia (AML)" and Change it to Acute Myeloid Leukemia (AML)-III
7. Update the page by clicking "Update" button on the top right side

Expected Result: When the Edit Page is updated, Change in Headings can be seen in the summary Block. 

Actual Result: when the Edit Page is updated, Change in Headings are not updated. 

![Summary1](https://user-images.githubusercontent.com/76508916/111106267-0386bf00-8512-11eb-8aed-3e6f6dfd10da.PNG)
![Summary2](https://user-images.githubusercontent.com/76508916/111106268-041f5580-8512-11eb-94fe-8916a0df2af6.PNG)
![Summary 3](https://user-images.githubusercontent.com/76508916/111106265-02ee2880-8512-11eb-950e-287487cef12f.PNG)

**Comment by htmgarcia** [comment]
@rishavarora you need to click the refresh icon on the block toolbar.
