### ISSUE TITLE
Summary Reference Links to the Headings, takes to middle of paragraph

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#352]
Steps to Reproduce:

1. Install and Activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress Block
4. Type "Summary" on the search bar then click "Summary" block
5. New Button block will appear on the Page Editor screen with its editing panel
6. Update the page by clicking "Update" button on the top right side
7. Click "any heading from the summary block

Expected Result: When Heading is clicked from summary block, It takes to the heading where every line of paragraph is visible.
Actual Result: When Heading is clicked from summary block, it takes you to middle of the paragraph.
![Summary4](https://user-images.githubusercontent.com/76508916/111107953-1c44a400-8515-11eb-8f8c-cbef1666ddff.PNG)

**Comment by htmgarcia** [comment]
@rishavarora that' due the theme in use has a fixed navigation menu. The heading is overlayed. Technically is not an issue.
