### ISSUE TITLE
Add more advanced layouts for Recent Posts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#360]
@htmgarcia One thing to think about ... can we provide more advanced layout options for the Recent Posts block?

For example, horizontal:
![Screen Shot 2021-03-16 at 2 50 28 PM](https://user-images.githubusercontent.com/3868028/111363907-faf3cd00-8666-11eb-8f1d-a2b90bacfba3.png)

Vertical:
![Screen Shot 2021-03-16 at 2 52 17 PM](https://user-images.githubusercontent.com/3868028/111364128-3b534b00-8667-11eb-8ed0-0f802726c276.png)

Major story with smaller stories:
![Screen Shot 2021-03-16 at 2 50 49 PM](https://user-images.githubusercontent.com/3868028/111363939-0810bc00-8667-11eb-8d5b-2c6af14cffe2.png)

**Comment by htmgarcia** [comment]
@stevejburge currently supports list, grid (columns) and slider as layout options. This suggestion seems closer to this block  #303

**Comment by stevejburge** [comment]
@htmgarcia Agreed. Maybe we don't need a separate block?

**Comment by htmgarcia** [comment]
@stevejburge depends, do we want the advanced layouts to be available in Pro version?

**Comment by stevejburge** [comment]
@htmgarcia Not necessarily, no. This block is already free

**Comment by htmgarcia** [comment]
Current progress: https://github.com/publishpress/PublishPress-Blocks/compare/develop...recent-posts-layouts-improvements

**Comment by htmgarcia** [comment]
At this point 4 styles are implemented for Frontpage view: default, boxed, newspaper and headline.

I see 2 potential issues with headline style:

- [ ] Force to display featured image always to not break the design and purpose of this style
- [ ] When the content can't fit the image and its container, crop through CSS

**Comment by htmgarcia** [comment]
A third issue:

- [ ] Link to author is overlayed for post link (aka. can't click on author)

**Comment by htmgarcia** [comment]
Fix for the third issue https://github.com/publishpress/PublishPress-Blocks/commit/c6a1d3d9c71b7ca2b38f182445a1d89115844e77

**Comment by htmgarcia** [comment]
> Major story with smaller stories:
> ![Screen Shot 2021-03-16 at 2 50 49 PM](https://user-images.githubusercontent.com/3868028/111363939-0810bc00-8667-11eb-8d5b-2c6af14cffe2.png)

@stevejburge to cover this requirement at some extent, I have a proposal:

### Enable "Featured Image"

<img width="263" alt="1" src="https://user-images.githubusercontent.com/4999794/113078394-41c9e280-9190-11eb-8f64-7f4613c7d89d.png">

### Choose to display to all posts o just for the first ones

<img width="265" alt="2" src="https://user-images.githubusercontent.com/4999794/113078404-45f60000-9190-11eb-9208-549c1664d5c5.png">

### End result

![featured-image-for-first-post-only](https://user-images.githubusercontent.com/4999794/113078423-4f7f6800-9190-11eb-9606-093240320bc6.png)

**Comment by stevejburge** [comment]
@htmgarcia Where's the fire emoji on here? This looks awesome!

**Comment by htmgarcia** [comment]
@stevejburge layouts are ready. Implemented a simple but essential improvement for Newspaper style to differentiate from the rest https://demo.publishpress.com/recent-posts-newspaper/

**Comment by stevejburge** [comment]
Thanks @htmgarcia. To be honest, this is the first one I've thought ... "that's a bit odd"

I'm not sure splitting the text works.

**Comment by htmgarcia** [comment]
Change reverted https://github.com/publishpress/PublishPress-Blocks/commit/ccc6c28aa2f247c09491d868514924e804668111

**Comment by htmgarcia** [comment]
@stevejburge new Newspaper proposal https://demo.publishpress.com/recent-posts-newspaper/
<img width="1266" alt="Screen Shot 2021-04-06 at 20 10 42" src="https://user-images.githubusercontent.com/4999794/113797217-78ff3d00-9716-11eb-8ddd-6b6ff1901878.png">
<img width="908" alt="Screen Shot 2021-04-06 at 20 09 42" src="https://user-images.githubusercontent.com/4999794/113797227-7b619700-9716-11eb-988d-6adb8b832bf8.png">

**Comment by stevejburge** [comment]
Looks awesome @htmgarcia

**Comment by htmgarcia** [comment]
@stevejburge more Newspaper layouts https://demo.publishpress.com/recent-posts-newspaper/
<img width="261" alt="Screen Shot 2021-04-07 at 19 29 45" src="https://user-images.githubusercontent.com/4999794/113950737-a9f37680-97d7-11eb-8fd3-4048d853f039.png">

**Comment by stevejburge** [comment]
@htmgarcia awesome, thanks

**Comment by htmgarcia** [comment]
@stevejburge added 5 Newspaper layouts variations placing the leading post in the right following one of your suggestions https://demo.publishpress.com/recent-posts-newspaper/
<img width="896" alt="Screen Shot 2021-04-08 at 20 36 56" src="https://user-images.githubusercontent.com/4999794/114116458-60c02700-98aa-11eb-9d4d-fb564fb7f83b.png">
