### ISSUE TITLE
Display categories or Tags in the layout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#361]
We have date, author, featured image etc

Can we also allow users to show the appropriate Categories and Tags?

- We may need to also allow a limit as this space is crowded
- We should allow the labels to be linked (to Archive pages) or unlinked 

Example:
<img width="802" alt="Screen Shot 2021-03-26 at 12 52 06 PM" src="https://user-images.githubusercontent.com/3868028/112666059-20849180-8e32-11eb-8127-577b0c38ba60.png">

Another example:
<img width="1414" alt="Screen Shot 2021-03-26 at 12 54 17 PM" src="https://user-images.githubusercontent.com/3868028/112666296-6a6d7780-8e32-11eb-83a0-b20c6e3df793.png">

**Comment by htmgarcia** [comment]
Adjust tags and categories style https://github.com/publishpress/PublishPress-Blocks/commit/d5203eb52bfd027fb001df4814792e0fe0d6ffb8
