### ISSUE TITLE
Masonry view for Recent Posts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#362]
![Screen Shot 2021-03-16 at 3 16 50 PM](https://user-images.githubusercontent.com/3868028/111367016-a4888d80-866a-11eb-95fb-1a012469c651.png)

**Comment by htmgarcia** [comment]
Is buggy in Twenty Twenty and  Twenty Twenty One theme when resizing the browser, plus in Twenty Twenty the container is not centered.

**Comment by htmgarcia** [comment]
The captions are overlayed.
