### ISSUE TITLE
News over image layout for Recent Posts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#363]
This is similar to our Grid view, but the items are on top of the image

![Screen Shot 2021-03-16 at 3 22 06 PM](https://user-images.githubusercontent.com/3868028/111367768-73f52380-866b-11eb-80a5-031ee28d1d43.png)

**Comment by htmgarcia** [comment]
@stevejburge this is covered on Frontpage view with Headline style: https://demo.publishpress.com/recent-posts-frontpage/
