### ISSUE TITLE
Configurable color for the Newspaper style

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#375]

**Comment by stevejburge** [comment]
@htmgarcia A couple of approaches here.

It could be configurable for each layout. Or we could skip this for all of them

**Comment by htmgarcia** [comment]
@stevejburge Recent Posts includes several new improvements and features. We can keep this suggestion on hold to think more about it and come back to it later?

**Comment by stevejburge** [comment]
@htmgarcia Thanks. Can we remove the added color for now, while we think?
