### ISSUE TITLE
Make Slider view look more like Frontpage with Headline style

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#376]

**Comment by htmgarcia** [comment]
@stevejburge headline style support for Slider view
<img width="939" alt="Screen Shot 2021-04-02 at 14 03 44" src="https://user-images.githubusercontent.com/4999794/113450012-4a066580-93bc-11eb-9179-3fbafd98518c.png">

**Comment by stevejburge** [comment]
@htmgarcia Awesome!
