### ISSUE TITLE
Mismatching in location of icons for desktop preview and live site view  

### ISSUE THREAD

**Issue by Sumitpalkaur** [publishpress/PublishPress-Blocks#377]
Steps to reproduce:
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. Type "Advanced Icons" on the left side search bar and click "Advanced Icons" block
5. Add any title name  and Select “Icon” and add 7 icons
6. Click "preview" and select desktop view, all 4 icons will be displayed horizontally and 3 in lower row .
![1](https://user-images.githubusercontent.com/78237378/112376309-87267580-8ca1-11eb-9a2a-f71127d0bf1e.PNG)

Expected results: Live site should display view same as the preview
Actual results: In View site live, 6 icons displayed horizontally and 1 icon under them 
![2](https://user-images.githubusercontent.com/78237378/112376322-8d1c5680-8ca1-11eb-87c8-f3d7bceeb4cb.PNG)

**Comment by htmgarcia** [comment]
@Sumitpalkaur thanks! This one is relative to the screen/device width.
