### ISSUE TITLE
Option to include the time in the layout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#383]
example here:
<img width="692" alt="Screen Shot 2021-03-26 at 12 40 50 PM" src="https://user-images.githubusercontent.com/3868028/112664614-88d27380-8e30-11eb-93fe-3ef1fed2e053.png">

**Comment by stevejburge** [comment]
One more example:
<img width="1153" alt="Screen Shot 2021-03-26 at 12 47 17 PM" src="https://user-images.githubusercontent.com/3868028/112665439-7147ba80-8e31-11eb-9572-98b8f069fa41.png">

**Comment by htmgarcia** [comment]
Display time setting only when date is enabled https://github.com/publishpress/PublishPress-Blocks/commit/f84d3e1c4b2268b67a284122850dceef6b8531db
Move "Display post time" below "Display post date" https://github.com/publishpress/PublishPress-Blocks/commit/31459b30e5e142aa6d74bfcbdec0f73108398b1f
