### ISSUE TITLE
Option to show "Updated ago" or "Updated date"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#385]
Examples:

<img width="778" alt="Screen Shot 2021-03-26 at 12 50 53 PM" src="https://user-images.githubusercontent.com/3868028/112665940-fb901e80-8e31-11eb-8e23-2d868b81c692.png">
<img width="388" alt="Screen Shot 2021-03-26 at 12 50 26 PM" src="https://user-images.githubusercontent.com/3868028/112665941-fc28b500-8e31-11eb-88e9-08988e6ff167.png">

**Comment by contactashish13** [comment]
@stevejburge @htmgarcia should this be given as an additional to the post date/time or should this and the post date/time option be mutually exclusive? I'm not sure what the use case for showing both post date/time and last updated would be

**Comment by stevejburge** [comment]
@contactashish13 I think that's a good idea. Perhaps users can choose from one of two options:

1. Posted Date
2. Updated Date

And then there's a format option:

1. Show as the plain date
2. Show as "time ago"

**Comment by htmgarcia** [comment]
@stevejburge with or without "Updated" / "Posted" words?

<img width="756" alt="Screen Shot 2021-03-31 at 10 27 03" src="https://user-images.githubusercontent.com/4999794/113178372-bee66d80-920b-11eb-96e8-4332f4eec24f.png">
<img width="752" alt="Screen Shot 2021-03-31 at 10 26 21" src="https://user-images.githubusercontent.com/4999794/113178379-bf7f0400-920b-11eb-8ea3-eb554afbc9d5.png">

**Comment by stevejburge** [comment]
With the words, please @htmgarcia
