### ISSUE TITLE
Feature by Author

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#387]
Would be great to add an "Author" filter similar to "Categories" and "Tags" but for Authors, including PublishPress Authors

That would allow you show all the recent posts from one Author

**Comment by htmgarcia** [comment]
@stevejburge @contactashish13 that filter seems possible with `QueryControls` https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/query-controls/index.js#L98-L107

**Comment by htmgarcia** [comment]
@contactashish13 we're now using a customizable QueryControls component named `AdvQueyControls` https://github.com/publishpress/PublishPress-Blocks/pull/404/files?file-filters%5B%5D=.jsx&file-filters%5B%5D=.txt#diff-ac0f04f872a1602dc723590d20cdc0357bc6caa100d9837296f5647319e6cc23
