### ISSUE TITLE
Image slider doesn't work with different sizes of images.

### ISSUE THREAD

**Issue by katerby** [publishpress/PublishPress-Blocks#388]
**Describe the bug**
After adding different size images into slider, it causes slider to expand to image size. After adjustment image size in the image settings, image lost at quality.

**To Reproduce**
1. Add different sizes of images to Image Slide Block
2. See it doesn't adapt to different sizes

Videos:
https://user-images.githubusercontent.com/77123682/112679046-1a96ac80-8e42-11eb-93ac-e9a4cdfff5eb.mp4

https://user-images.githubusercontent.com/77123682/112679054-1b2f4300-8e42-11eb-9208-03c53e620ff4.mp4

**Expected behavior**
Would be nice if slider could adapt to different sizes of images without loosing image quality

**Desktop (please complete the following information):**
 Windows 10,
Microsoft Edge

**Comment by htmgarcia** [comment]
Thanks @katerby ! Not an issue, really. The slides text with or without image would use the height depending the content height. We may consider applying [this improvement](https://github.com/publishpress/PublishPress-Blocks/issues/376) into Images Slider.

**Comment by htmgarcia** [comment]
Opened a new issue #416
