### ISSUE TITLE
HTML before and after the Recent Posts block

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#390]
![Screen Shot 2021-03-26 at 4 21 52 PM](https://user-images.githubusercontent.com/3868028/112688574-7582d080-8e4f-11eb-92c2-09617112ed38.png)

**Comment by htmgarcia** [comment]
@stevejburge a Custom HTML or Paragraph block before and after Recent Posts would cover this, imho.

**Comment by stevejburge** [comment]
@htmgarcia Should could come under the title, or before the readme

**Comment by htmgarcia** [comment]
@stevejburge is this aligned to the result we expect?
![image](https://user-images.githubusercontent.com/12953439/113246439-aa22dc00-92d6-11eb-8873-6490084cb74a.png)

**Comment by stevejburge** [comment]
@htmgarcia Yes, please
