### ISSUE TITLE
In advanced button block, submenu margin right is not functional

### ISSUE THREAD

**Issue by Sumitpalkaur** [publishpress/PublishPress-Blocks#392]
**Describe the bug**
In configurations of Advanced button, option 'margin top' is non functional.

**To Reproduce**
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit
3. Click "+/plus" sign to add a new PublishPress block
4. Type "Advanced Button" on the search bar and click "Advanced Button" block
5. “Add title” and “Push to Button” will be displayed
6. Add title as “Push a button" and by default a blue button with inbuilt text "Push to button" appears.
7. To modify the style of the push button, scroll down the configuration options appear on the right side.
8. Click on the "Margin" menu. Drag the pointer on slide of  "margin right"4 to increase the value.
9. See error- Block remains at same position.

**Expected behavior**
Block should move towards right on increasing the value.

** Actual behavior**
Block position doesn't change with increasing the value of margin right
**Desktop (please complete the following information):**
 - OS: 64 bit
 - Browser - chrome
 - Version [ 89.0.4389.90]

**Comment by htmgarcia** [comment]
@Sumitpalkaur since the buton is aligned to the left, visually is not possible to see the margin-right however I confirm is there.
