### ISSUE TITLE
Currently all items in the have the same size

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#402]
Can we allow users to wrap elements in h1, h2, h3, div, paragraph etc?
<img width="784" alt="Screen Shot 2021-03-30 at 10 16 44 AM" src="https://user-images.githubusercontent.com/3868028/113003901-28e61080-9141-11eb-9adf-4dc304e47bee.png">

**Comment by htmgarcia** [comment]
@stevejburge may you elaborate?

**Comment by htmgarcia** [comment]
btw, post titles now will inherit the h2 font-size from theme in use

**Comment by htmgarcia** [comment]
@stevejburge yes, same case for the rest of text, except for categories and tags. Size is proportionally resized but still based on theme CSS.
