### ISSUE TITLE
Space between columns can't be seen on edit

### ISSUE THREAD

**Issue by katerby** [publishpress/PublishPress-Blocks#403]
**Describe the bug**
Block Columns Manager- Change of space between columns can be seen only in View Post mode

**To Reproduce**
1. Add Block Columns Manager
2. Go to settings of the block
3. Change Space between columns
4. Nothing happens in edit post mode (can seen only in view post mode)

**Expected behavior**
With each change of pixels (space between columns) , space between columns should adjust accordingly in edit mode.

**Comment by htmgarcia** [comment]
I'm not able to reproduce. The space between columns works in editor.
