### ISSUE TITLE
Feature to add more than one receiver is not working

### ISSUE THREAD

**Issue by Sumitpalkaur** [publishpress/PublishPress-Blocks#426]
**Describe the bug**
In contact block form, adding emails of more than one receiver at same time shows error message.

To Reproduce**
1. Install and activate "PublishPress Blocks" plugin
2. Go to “Add New post” or choose a post to edit.
3. Add title as "Contact form block"
4. Click "+/plus" sign to add a new PublishPress block.
5. Type "Contact form" in search box and click on appeared "contact form" block.
5. On right side click on "settings" under "form settings" in "Notice" message
6. Email & form page opens.
7. Type two valid email addresses in receiver email edit box .Separate them with comma in between as per guidelines.
8. Click "Save button"  

**Expected behavior**
All the information should be saved w/o warning

**Actual Behaviour
On clicking 'Save" button a warning message pop up saying "A part following @ should not contain symbol " ".

**Screenshot attached

**Desktop (please complete the following information):**
 - OS: [64-bit]
 - Browser [chrome]

![comma](https://user-images.githubusercontent.com/78237378/113673248-988e5b00-966d-11eb-8583-898a8e9f70f6.PNG)

**Comment by htmgarcia** [comment]
Thanks @Sumitpalkaur !
