### ISSUE TITLE
 Advanced Image Left alignment shows black screen 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#429]
Description : 
When Advanced image alignment is changed to left which is added to accordion header, Shows black screen. 

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced accordion" on the search bar then click "Advanced Accordion" block
5. New Accordion block will appear on the Page Editor screen with its editing panel
6. Click top Header from accordion block, block Collapses
7. Click "+" sign to add a new PublishPress block
8.  Type "Advanced Image" on the search bar then click "Advanced Image" block.
9.  New Image block will appear on the Page Editor screen with its editing panel
10.  Click "Open Media Library" and select image to Add. 
11. Click alignment from floating bar and choose "left"
12. Turn on "Full Width" from Advanced image side editor panel.

**Expected Result**
When Advanced image alignment from floating bar is changed to left which is added to accordion header, the image is aligned to the left. 

**Actual Result
When Advanced image alignment is changed to left which is added to accordion header, black image is displayed.

Desktop :**
 - OS- Windows 10
 - Browser - Chrome 
 

**Screenshots**
![123](https://user-images.githubusercontent.com/76508916/113814742-f59a1780-9726-11eb-903f-a2989216ba44.PNG)

![accordianimage123](https://user-images.githubusercontent.com/76508916/113814513-a2c06000-9726-11eb-90f0-f0b6aacd556b.PNG)

**Comment by htmgarcia** [comment]
Duplicated #438
