### ISSUE TITLE
Advanced image added to Advanced Accordion overlaps when alignment changes. 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#438]
Description :
An Advanced image added to Advanced Accordion overlaps when alignment is changed to Left 

Steps to reproduce: 

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced accordion" on the search bar then click "Advanced Accordion" block
5. New Accordion block will appear on the Page Editor screen with its editing panel
6. Click top Header from accordion block, block Expands
7. Click "+" sign to add a new PublishPress block
8. Type "Advanced Image" on the search bar then click "Advanced Image" block.
9. New Image block will appear on the Page Editor screen with its editing panel
10. Click "Open Media Library" and select image to Add-> Choose an image from Library
11. Click on Editing panel of Advanced Image 
12. Under Image Size Disable "Full Width" from Advanced image side editor panel.
13.  Click alignment from floating bar and choose "left"
14. Click Update. 

Expected Result: 
When an Advanced image added to Advanced Accordion(under body of first header) while full width is disabled and header is expanded-> alignment is changed to Left, Image is aligned on Left side. the second header overlaps on the image when alignment changed to Left.

Actual Result
When an Advanced image added to Advanced Accordion(under body of first header) while full width is disabled and header is expanded,  the second header overlaps on the image when alignment changed to Left.

Desktop :

OS- Windows 10
Browser - Chrome

Screenshot: 
![1234567](https://user-images.githubusercontent.com/76508916/114256405-e5c04480-996d-11eb-9015-eabaef36c3bc.PNG)
![123456](https://user-images.githubusercontent.com/76508916/114256408-ea84f880-996d-11eb-9a17-eb59ee4f76b9.PNG)

**Comment by htmgarcia** [comment]
I was able to reproduce this issue. Thanks @rishavarora !

Frontend: This is how loads by default and when opening the accordion:
![Screen Shot 2021-05-06 at 16 06 09](https://user-images.githubusercontent.com/4999794/117365530-07392100-ae85-11eb-8f9c-117f7f2d5b51.png)

Admin:
![Screen Shot 2021-05-06 at 16 07 14](https://user-images.githubusercontent.com/4999794/117365592-23d55900-ae85-11eb-912e-06d8638202d6.png)

**Comment by htmgarcia** [comment]
Technically is not an issue
