### ISSUE TITLE
Can't ignore src/assets/blocks/frontend.js.map file

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#440]
The ignore line rule is on .gitignore, however doesn't work.

**Comment by htmgarcia** [comment]
@contactashish13 why do you think the ignore rule isn't working?

**Comment by contactashish13** [comment]
@htmgarcia I think it is because the file is [already in the repo](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/assets/blocks/frontend.js.map). If we remove it, gitignore should work. Or we can try [this answer](https://stackoverflow.com/a/1274447) instead

**Comment by htmgarcia** [comment]
@contactashish13 Thanks! Very odd the same rule worked for blocks.js.map. 

https://github.com/publishpress/PublishPress-Blocks/commit/e076ad1f85feb2e6cdff1f80eaf3d9815c8cb3b2
