### ISSUE TITLE
Replace the "Profiles" setting with User Roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#442]
I think our use of "Profiles" is limiting for users. Who wants more groups to manage?

Would it make sense to show user roles here instead? @htmgarcia 

<img width="1376" alt="Screen Shot 2021-04-13 at 10 50 46 AM" src="https://user-images.githubusercontent.com/3868028/114573179-26f27600-9c46-11eb-8b6f-88db868d410f.png">

**Comment by htmgarcia** [comment]
@stevejburge may you elaborate?

**Comment by stevejburge** [comment]
@htmgarcia yes, and showing the roles on this screen.

In short, we would move closer to the WordPress core

**Comment by htmgarcia** [comment]
@stevejburge thanks for the clarification! Showing the roles on this screen is not possible due PP Blocks is designed to have multiple profiles. If the plan is get rid of profiles approach at all, I see your point.

**Comment by stevejburge** [comment]
@htmgarcia maybe we do that and just go with roles.

**Comment by htmgarcia** [comment]
@stevejburge we need to think carefully the process due the backward compatibility for sites having more than one profile. With this change multiple instances of user roles won't be allowed.

imho, this is something for version 3.0.0.

**Comment by stevejburge** [comment]
Sounds like a plan, thanks @htmgarcia

**Comment by stevejburge** [comment]
@htmgarcia Maybe a quick solution is to provide a default "All Users" profile?

![Screen Shot 2021-04-21 at 10 23 48 AM](https://user-images.githubusercontent.com/3868028/115570081-d43f3c80-a28b-11eb-91f3-6a3d265a6db1.png)

**Comment by htmgarcia** [comment]
@stevejburge good points. I'll take care of it.

**Comment by htmgarcia** [comment]
@stevejburge proposal:
![Screen Shot 2021-05-31 at 17 50 56](https://user-images.githubusercontent.com/4999794/120247365-c68cb780-c238-11eb-92ea-c1ba2fdbf8ef.png)
![Screen Shot 2021-05-31 at 18 01 15](https://user-images.githubusercontent.com/4999794/120247765-41a29d80-c23a-11eb-890c-9eac8e280248.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia. This looks great. 

- Should we call this "All User Roles"?
- Should we change the name of this menu / feature to "Block Access"? That makes more sense than "Profile"

**Comment by htmgarcia** [comment]
@stevejburge all set.
