### ISSUE TITLE
Update ADVGB text in blocks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#443]
<img width="788" alt="Screen Shot 2021-04-13 at 1 36 47 PM" src="https://user-images.githubusercontent.com/3868028/114596231-5eb8e800-9c5d-11eb-861e-f0b133ce7cfb.png">

**Comment by htmgarcia** [comment]
@stevejburge current result:
<img width="765" alt="Screen Shot 2021-04-13 at 15 57 23" src="https://user-images.githubusercontent.com/4999794/114620203-f7a52e80-9c70-11eb-9559-e4c8f30cac1e.png">

Any suggestion to improve the "not found" text?

**Comment by stevejburge** [comment]
@htmgarcia works great
