### ISSUE TITLE
Recent Posts Headline style could do better on smaller screens

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#447]
https://demo.publishpress.com/recent-posts-headline/

Widescreen:
![Screen Shot 2021-04-13 at 2 54 04 PM](https://user-images.githubusercontent.com/3868028/114605469-1f43c900-9c68-11eb-8068-ba1f335bd9d4.png)

Smaller screen:
![Screen Shot 2021-04-13 at 2 54 34 PM](https://user-images.githubusercontent.com/3868028/114605535-2e2a7b80-9c68-11eb-9b4d-ae87d3624fba.png)

**Comment by htmgarcia** [comment]
@stevejburge this one may vary from theme to theme and image size. We can consider a control for title font-size with responsive support.

**Comment by htmgarcia** [comment]
Moved to #478
