### ISSUE TITLE
Rename "Recent Posts" block to "Content Display"

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#449]
Include "recent posts" as keyword so the block can be found under the old name.
<img width="368" alt="Screen Shot 2021-04-13 at 15 46 45" src="https://user-images.githubusercontent.com/4999794/114618970-9e88cb00-9c6f-11eb-8087-1d182e8d7189.png">

**Comment by htmgarcia** [comment]
@stevejburge the description may need some improvements:
<img width="262" alt="Screen Shot 2021-04-13 at 15 45 40" src="https://user-images.githubusercontent.com/4999794/114618761-5cf82000-9c6f-11eb-8665-32606bdb63db.png">

> Display your posts in grid, list, slider, frontpage and newspaper view with beautiful layouts, styles and several settings and filters. This block was previously called "Recent Posts".

**Comment by stevejburge** [comment]
Thanks. "Displays your content in grid, list, slider, frontpage, and newspaper views with beautiful layouts and styles."

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks/commit/84679f8c5a393b882b2af1e64f329a793f1727fa
