### ISSUE TITLE
Submit button in Newsletter block is bounded

### ISSUE THREAD

**Issue by Sumitpalkaur** [publishpress/PublishPress-Blocks#464]
**Describe the bug**
In newsletter block, button "submit" has no option to change its position in any direction.

**To Reproduce**
1.Install and activate "PublishPress Blocks" plugin
2.Go to “Add New post” or choose a post to edit.
3.Add title as "Newsletter block"
4. Click "+/plus" sign to add a new PublishPress block.
5. Type "Newsletter" in search box and click on appeared "Newsletter" button.
6. Try to change the position of 'Submit' button

**Expected behavior**
Should be able to resize or relocate the 'Submit' button. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

![newsletter submit button](https://user-images.githubusercontent.com/78237378/115176459-ff564000-a081-11eb-8e97-92095a817fac.PNG)

**Comment by htmgarcia** [comment]
Duplicated. Closing in favor of #397
