### ISSUE TITLE
Social media icons colors options (Social links block)

### ISSUE THREAD

**Issue by katerby** [publishpress/PublishPress-Blocks#468]
**Describe the bug**
That is a suggestion for improvement: Why not to customize social media icons with their original look (colors)?

**To Reproduce**
1. Add Social links block
2. Go to Settings on the right side
3. In Preset icons- choose any icons (Facebook, Instagram for example)
4. Go to Preset Icon color (I can choose color for each icon separately/customize color) 

**Expected behavior**
Choose customized social media icons with original colors  ( For example: Instagram icon is memorized not only by icon shape, but colors as well (we cannot customize that colors in block manually))  

**Desktop (please complete the following information):**
 - Windows 10

**Comment by htmgarcia** [comment]
@katerby the color picker allows to choose any color.
