### ISSUE TITLE
Add custom styles to any block

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#47]
>  I really like how the custom styles feature works. As a theme developer, this lets me control the look and consistency a lot more than giving users the ability to edit colors and icons manually (which also quickly becomes a nightmare to update and maintain).
> 
> However, it's fairly limited in its use since it works only on the paragraph block as far as I can tell. I would really love if this could just be added to every block, so the writers can easily add a style. I know this is achievable by just typing the style name in the advanced area, but then they have to remember all the possibilities. I really like the drop-down and color coding.

**Comment by htmgarcia** [comment]
This will be covered in #472
