### ISSUE TITLE
Improvements to use of custom styles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#472]
Can we make them more visible in the admin area? Maybe a dropdown somewhere?

Using the "Advanced" box isn't easy:
<img width="389" alt="Screen Shot 2021-04-21 at 10 27 06 AM" src="https://user-images.githubusercontent.com/3868028/115570480-2718f400-a28c-11eb-9378-248c95039cc8.png">

**Comment by htmgarcia** [comment]
@contactashish13 we have this feature working only for paragraph blocks through a separate attribute named `customStyle` at https://github.com/publishpress/PublishPress-Blocks/tree/master/src/assets/blocks/customstyles

However we expect a similar approach like [Block Animations](https://wordpress.org/plugins/blocks-animation/) plugin which directly modify `className` attribute, so we can preview the result in admin as well.

**Comment by htmgarcia** [comment]
@stevejburge due the possible incompatibilities with the styling of some block types, I suggest this feature for selected blocks only. As example: paragraphs, headings, lists, groups.

**Comment by stevejburge** [comment]
@htmgarcia Agreed. This could also make the feature clearer and more useful
