### ISSUE TITLE
Clicking on the sides of the editor scrolls down to the bottom

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#477]
This happens when PP Blocks is activated.
![Untitled-1](https://user-images.githubusercontent.com/4999794/115639189-9832c880-a2d9-11eb-94ae-f34f02847615.jpg)

**Comment by contactashish13** [comment]
@htmgarcia I'm unable to reproduce this. Here are the steps I followed:
- deactivate PP blocks
- create a post
- activate PP blocks
- edit the post, insert a block (content display, in grid format)
- click on the sides - the page does not scroll, the block gets deselected

**Comment by htmgarcia** [comment]
@contactashish13 try clicking on the post title first, then on the sides.

**Comment by contactashish13** [comment]
@htmgarcia still doesn't work for me. Could you possibly share a video? I'm probably doing something wrong.

**Comment by htmgarcia** [comment]
@contactashish13 sure thing
https://user-images.githubusercontent.com/4999794/116432442-3b21a000-a80e-11eb-943b-41979d8c30b5.mov

**Comment by contactashish13** [comment]
@htmgarcia thanks but still no luck. I tried adding different blocks to the post (it is just a post with a lot of text and one PP block) but with the same result. I have attached a video of my attempt with the button block added to the post. 


https://user-images.githubusercontent.com/12953439/116509476-fdda1280-a8e0-11eb-87b1-34f1f369acc9.mp4

**Comment by htmgarcia** [comment]
@contactashish13 I can see in your test the cursor in the sides is the default while in my end is the text one.
I'm using MacOS Big Sur in Firefox. Which OS and browser are you using?

**Comment by contactashish13** [comment]
@htmgarcia I use Chrome on Windows but I tested on Firefox as well just now and I get the same behavior as before.

**Comment by htmgarcia** [comment]
Even when Blocks is disabled, I'm able to reproduce this. It seems when the mouse cursor changes to text (outside the blue area from screenshot below), after doing click scrolls down the page.
![Screen Shot 2021-05-28 at 12 46 58](https://user-images.githubusercontent.com/4999794/120023580-997ba300-bfb3-11eb-93ec-7dfada25aad3.png)

@contactashish13 are you able to reproduce this behavior when PP Blocks is deactivated and activated?

**Comment by htmgarcia** [comment]
In a new test, #540 could solve this issue.  Waiting on customer feedback.
