### ISSUE TITLE
Control title in Content Display

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#478]
For some views, we don't need the title

The 3 tasks for title: 
- [x] Control font-size based on screensize (desktop, tablet, mobile) (inherit from theme is default)
- [x] Set custom color (inherit from theme is default)
- [x] Display/hide based on screensize, in particular useful for Frontpage's Headline style (desktop, tablet, mobile)

Edit by @htmgarcia

**Comment by htmgarcia** [comment]
Complementary to #465

**Comment by htmgarcia** [comment]
Related to #447

**Comment by htmgarcia** [comment]
@stevejburge I've merged other issues related on this one. Added a list on the first comment.
