### ISSUE TITLE
Hypertext link text color cannot be changed 

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#487]
**Describe the bug**
Hypertext link color in a advanced table cell cannot be changed

**To Reproduce**
1.  Install and activate "PublishPress Blocks" plugin
2. Go to a Pages and choose the page that needs to be edited
3. Click "+" sign to add a new PublishPress block
4. Type "Advanced Table" on the search bar then click "Advanced Table" block
5. New  block appear on the Page with Column and Row Count. 
6. Enter "3" to Row and "3" to columns and press create
7. Table appear showing 3 colums and 3 rows with the Page Editor screen with its editing panel
8. Enter Data into Rows and colums 
9. Highlight any cell from this table 
10. From the Floating bar Menu, Click Link and enter" https://www.cancer.gov/about-cancer/causes-prevention" and  Submit
11. From Editing panel, Click Cell setting and pick a color for "Text Color"-> Pink.
12. Click Update.

**Expected behavior**
When a table cell with hyperlink is selected and change is made to text color, default Black color is changed to selected Pink, 

**Actual behavior*
When a table cell with hyperlink is selected and change is made to text color, default Black color stays.

**Screenshots**
![12345678](https://user-images.githubusercontent.com/76508916/115935232-97b84000-a447-11eb-9329-b2391299c778.PNG)
![123456789](https://user-images.githubusercontent.com/76508916/115935234-9850d680-a447-11eb-8399-9de46b23403b.PNG)

**Desktop :**
 - OS: Windows 10
 - Browser : Chrome
 - Version : 89.0.4389.128

**Additional context**

**Comment by htmgarcia** [comment]
@rishavarora custom link color works in my end. If I'm missing something, please let me know.
