### ISSUE TITLE
When having more than one block with CPT 

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#489]
When having 2 blocks displaying CPT, the second one is empty in front.

1. Create two Content Display blocks
2. Choose a CPT for both. It can be the same CPT for both or different (except pages and posts).
3. The admin display both blocks correctly but not the front

**Comment by contactashish13** [comment]
@htmgarcia I cannot reproduce this. I have attached a screen recording.

https://user-images.githubusercontent.com/12953439/116334575-1409a500-a7f3-11eb-89d4-e0c265bc8a1a.mp4

**Comment by htmgarcia** [comment]
I'm no able to reproduce this anymore.
