### ISSUE TITLE
 In "Login/Register Form" block, after enabling the "Show register/header link", the "Show lost password link" option disappears

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Blocks#50]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Login/Register Form" option
Step 5:   Open "Form State" menu
Step 6:   Enable "Show register/header link"
 
![image](https://user-images.githubusercontent.com/62157750/84302747-ad13cc80-ab0a-11ea-85da-73ecc8d0df28.png)

Note: The "Show lost password link" option will be available anymore (no matter the state of this option: enable or disable)

![image](https://user-images.githubusercontent.com/62157750/84302760-b3a24400-ab0a-11ea-970b-80ba0ffd6b85.png)

**Comment by htmgarcia** [comment]
Definitely I see an odd behavior here after changing the defaults.

**Comment by htmgarcia** [comment]
@JulieBanu ok. I see what's causing the confusion. If user registration is disabled from General settings, it affects this block result.
<img width="405" alt="Screen Shot 2021-01-11 at 14 47 19" src="https://user-images.githubusercontent.com/4999794/104236329-fbc87280-541b-11eb-8037-24d1a481c39a.png">
Please reopen if needed.
