### ISSUE TITLE
In "Map" block, "Fetch Location" button is not working

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Blocks#51]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Map" option
Step 5:   Fill in "Address" field
Step 6:   Click "Fetch Location" button
 
Note: the location does not change on the map (Eiffel Tour was the default location)
![image](https://user-images.githubusercontent.com/62157750/84318062-adb85d00-ab22-11ea-8911-fc2c89f551da.png)

**Comment by htmgarcia** [comment]
I get in console:
`Geocoding Service: This API project is not authorized to use this API.  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

**Comment by htmgarcia** [comment]
In addition to Maps JavaScript API, is also required to enable Geocoding API and problem solved.
