### ISSUE TITLE
No Error Message on Protected Password Post

### ISSUE THREAD

**Issue by rishavarora** [publishpress/PublishPress-Blocks#511]
Summary: No Error Message is generated with wrong password on Protected Password Post 

Steps to Reproduce:

1. Install and activate "PublishPress Blocks" plugin
2. Go to a Post and choose the Post that needs to be edited
3. Page opened with the post to be edited with editior panel on the right. 
4. Choose Page from the Editot Panel tab
5. Click Visibility and change it to Password Protected 
6. Enter your choice password for this post
6. Click "Update"
7. Click "Preview in new tab"
8. Enter Wrong Password 

Expected Result: When Wrong password is entered to Password Protected Post, Error Message window appears " Wrong Password" 

Actual Result: When Wrong password is entered to Password Protected Post, No Error message apperas.  

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: Google Chrome, Safari
 
Screenshot: 
![passwordprotected1](https://user-images.githubusercontent.com/76508916/118381215-73123c80-b59d-11eb-961a-d666acf02d23.PNG)

![passwordprotected](https://user-images.githubusercontent.com/76508916/118381213-7279a600-b59d-11eb-9ece-4f910780bdb9.PNG)

**Comment by htmgarcia** [comment]
The post password protection is not related to a Gutenberg plugin.
