### ISSUE TITLE
Error with Custom Post Type UI

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#538]
I see this error flash across the screen with Blocks Pro when I'm using the Custom Post Type UI plugin:

<img width="1680" alt="Screen Shot 2021-05-25 at 8 20 23 AM" src="https://user-images.githubusercontent.com/3868028/119514406-3a5b2b80-bd32-11eb-96aa-f312c6be06c3.png">

**Comment by htmgarcia** [comment]
Related to #535
