### ISSUE TITLE
Category and Tag bubbles may look to similar in Content Display Block

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#542]
![Screenshot (8)](https://user-images.githubusercontent.com/79052272/119600401-349e2e00-bda4-11eb-8177-139b17e21ed6.png)
![Screenshot (9)](https://user-images.githubusercontent.com/79052272/119600406-3667f180-bda4-11eb-8892-515a2d7b871f.png)

While playing around with the Content Display Block, I noticed that the design of Categories and Tags look fairly similar to each other accept for a slight size difference. Even between themes they are still similar. I was wondering if changing the shape of the bubble or maybe change the color of the background in the bubble might help distinguish between the Categories and Tags.

**Comment by htmgarcia** [comment]
@Bachynski that's on purpose. The difference is the size. Categories are bigger and uppercase.
