### ISSUE TITLE
Posted Date and Time not Consistent Between Saved Time Zone, Dashboard Post, and View of Post on Website

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#543]
**Describe the bug**
When posting Content Display material via the dashboard, noticed the posted dates were not of the same time zone as in the software saved settings. However, if one were to navigate to the post on the website, the post date and time are correct.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Settings' tab
3. Click on 'Settings' tab
4. Set 'Time zone' as Edmonton and Save changes
5. Observe post with Content Display Block via Dashboard and Website Post

**Expected behavior**
Expected the date and time to be consistent when viewed from either the Dashboard or website.

**Screenshots**
![Screenshot (11)_LI](https://user-images.githubusercontent.com/79052272/119602158-ce1b0f00-bda7-11eb-8e4f-05785ff912f4.jpg)
![Screenshot (12)_LI](https://user-images.githubusercontent.com/79052272/119602167-d1ae9600-bda7-11eb-96c4-191c7ae333b7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.77

**Smartphone (please complete the following information):**
 - N/A

**Comment by htmgarcia** [comment]
@Bachynski I was able to reproduce the issue. Thanks!
