### ISSUE TITLE
Property Display Post Excerpt does not works

### ISSUE THREAD

**Issue by hfridland** [publishpress/PublishPress-Blocks#546]
**Describe the bug**
Excerpt does not seen on Content Display component even if property Display Post Excerpt set to true

**To Reproduce**
1. Create WordPress site and install PublishPress
2. Add some posts with excerpt
3. Add page, put Content Display plugin
4. Set Display Post Excerpt to On
5. Excerpt does not seen

**Expected behavior**
If Display Post Excerpt set to on Excerpt seen.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hfridland** [comment]
Desktop (please complete the following information):

    OS: Windows
    Browser: Firefox
    Version: 88.0.1

**Comment by htmgarcia** [comment]
@hfridland excerpt is displayed in my end.  Te only case where is not displayed is for the posts that does't have one (empty excerpt)
![Screen Shot 2021-06-01 at 16 00 37](https://user-images.githubusercontent.com/4999794/120389874-9e618f00-c2f2-11eb-9015-79e43f7dc7e4.png)
![Screen Shot 2021-06-01 at 16 00 24](https://user-images.githubusercontent.com/4999794/120389876-9f92bc00-c2f2-11eb-9dc6-78a7d0231b1d.png)
