### ISSUE TITLE
Wrap around Category and Tag bubbles don't look too appealing

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#547]
I've noticed when publishing using 'Content Display' Blocks, particularly with the 'Front Page' and 'Newspaper' views, that if the text of a Category or Tag is too long to fit in the article it wraps around to fit the space available. With the current bubble outline text looks cut-off and is unappealing.

Removing the outline lets the text wrap but doesn't give the immediate appearance of being cut-off

The bubbles are a nice feature, when it works, so if one were to keep the outline maybe limiting the characters per Category or Tag might be a solution. Or maybe letting the bubbles scale to keep from wrapping.

![Frontpage View Category Text Wraps if too long; does not look appealing edit](https://user-images.githubusercontent.com/79052272/119712890-54723800-be1e-11eb-9ef7-89d183b5b471.png)
![Newspaper View Category Text Wraps if too long; does not look appealing edit](https://user-images.githubusercontent.com/79052272/119712904-5936ec00-be1e-11eb-8ae3-f2b46c9c2047.png)

**Comment by htmgarcia** [comment]
@Bachynski thanks for your feedback! I'm afraid there is no solution for this one. I could force to display the label on a single line but the tag/category would be cropped due the available width won't be enough. In this scenario the setup of the Content Display block (such as number of columns and the available width for the block inside the theme) is under user's discretion and may generate this result.

An alternative solution is to allow custom font-size, with optional sizes for tablets and mobiles. This will allow long labels to fit in the same line. 

I'm closing this issue in favor of #567

**Comment by htmgarcia** [comment]
This is a great suggestion, btw.
> maybe limiting the characters per Category or Tag

**Comment by htmgarcia** [comment]
This was the working approach that worked.
![Screen Shot 2021-06-01 at 14 57 03](https://user-images.githubusercontent.com/4999794/120384393-b681e000-c2eb-11eb-84dc-c0d3ac8baa99.png)
