### ISSUE TITLE
Number of items is displayed incorrectly in Masonry View

### ISSUE THREAD

**Issue by sathyapriya91** [publishpress/PublishPress-Blocks#549]
**Describe the bug**
The chosen number of items should be displayed in Masonry view block.

**To Reproduce**
1. Open Word Press and create a New Post
2. Select Add Block -> Content Display
3. Go to "Masonry view" of content display
4. From Block-> Post settings, Set the Number of items to "1" 
5. Increase the Number of items to 2 

**Expected behavior**
Two items should be displayed in the block instead of one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Chrome
 - Version: 6.2

**Smartphone (please complete the following information):**

**Additional context**
![column setting](https://user-images.githubusercontent.com/83974581/119734980-8e4c3a00-be30-11eb-9654-65bd9f460b31.JPG)
![Number of items](https://user-images.githubusercontent.com/83974581/119734983-8ee4d080-be30-11eb-8b34-38e746c58c28.JPG)

**Comment by Bachynski** [comment]
Cannot be reproduced:

Windows 10
Chrome
Version: 91.0.4472.77

**Comment by htmgarcia** [comment]
@sathyapriya91 please click the "refresh"button. That will rebuild the preview.
![Screen Shot 2021-05-28 at 15 06 46](https://user-images.githubusercontent.com/4999794/120037152-c8e7db00-bfc6-11eb-9340-e8b286885180.png)
