### ISSUE TITLE
Support for custom taxonomies in Content Display

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#552]
Would be great if we could support custom taxonomies in the Content Display block.

For example, you could show all posts with a specific PublishPress status

**Comment by htmgarcia** [comment]
@stevejburge you can already filter content by taxonomies. See the Filters panel, please.
![Screen Shot 2021-05-27 at 10 50 03](https://user-images.githubusercontent.com/4999794/119857605-53eaa780-bed9-11eb-9e79-76d90f642b39.png)

**Comment by htmgarcia** [comment]
The feature already exists. Reopen if I'm missing something.
