### ISSUE TITLE
Different icons for lists

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#554]
What if we want different icons for each item? Currently possible by creating different instances of the block, which is not good for UX:
![Screen Shot 2021-05-27 at 14 03 51](https://user-images.githubusercontent.com/4999794/119882809-70e0a400-bef4-11eb-823e-5d2dd5b10250.png)

We can think this as an improvement for Adv List or for a new block.

**Comment by stevejburge** [comment]
@htmgarcia a big thumbs up to this one
