### ISSUE TITLE
Frontpage View does not display  full text on the image

### ISSUE THREAD

**Issue by sathyapriya91** [publishpress/PublishPress-Blocks#556]
**Describe the bug**
In Frontpage view , the given full text is not displayed on the image in "headline style".

**To Reproduce**
1. Open Word Press and create a new post
2. Select Add Block -> Content Display
3. Select Frontpage View
4. Select Settings -> Block -> Frontpage view settings
5. Select Style -> Headline
6. Select "All posts in 5 columns grid"/"All posts in 4 columns grid".

**Expected behavior**
The  image might be displayed with full text on the image just like in Default style and Boxed style for better display of the contents.

**Screenshots**
![Default style in Frontpage](https://user-images.githubusercontent.com/83974581/119901415-bd2ee280-befa-11eb-86aa-2f46921d06f7.JPG)
![Headline style in frontpage](https://user-images.githubusercontent.com/83974581/119901418-bdc77900-befa-11eb-9a7d-56dba5232e91.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Chrome
 - Version 6.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by htmgarcia** [comment]
Duplicated #478
