### ISSUE TITLE
"Text after title" and "Text before read more" accepts N number of characters.

### ISSUE THREAD

**Issue by sathyapriya91** [publishpress/PublishPress-Blocks#557]
**Is your feature request related to a problem? Please describe.**
'Text after title' and 'Text before read more' accepts N number of characters (In settings->block). It does not look appealing with too much contents in it.

**Describe the solution you'd like**
It would be nice to have a limit to the text in both 'text after title' and 'text before read more'.

**Describe alternatives you've considered**
It would be nice, if it displays only a certain number of characters and continues with ".." sign, even if accepts N number of characters.

**Additional context**

**Comment by htmgarcia** [comment]
@sathyapriya91 since is a free area to inject some content, this limitation is not required.
