### ISSUE TITLE
Add description for the columns

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#558]
This is easy to read with the descriptions:
<img width="785" alt="Screen Shot 2021-05-27 at 7 10 52 PM" src="https://user-images.githubusercontent.com/3868028/119915268-61c31b80-bf1f-11eb-91f0-7c3c28d653ee.png">

Our columns block is not so easy:
<img width="810" alt="Screen Shot 2021-05-27 at 7 10 45 PM" src="https://user-images.githubusercontent.com/3868028/119915281-6982c000-bf1f-11eb-8362-3811fac4b83b.png">

**Comment by htmgarcia** [comment]
@stevejburge improved proposal:
![Screen Shot 2021-07-05 at 15 42 16](https://user-images.githubusercontent.com/4999794/124516691-de130f00-dda7-11eb-97be-c42b4f5f5657.png)

**Comment by stevejburge** [comment]
@htmgarcia thumbs up
