### ISSUE TITLE
While in 'Masonry View' first two posts over-lap when adjusting number of items.

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#561]
Description:
When decreasing the number of viewable items to 1 and then increasing them to 2, the first two posts overlap.

1. Log into WordPress dashboard
2. Must have 2 posts already created
3. Click 'Posts' Tab
4. If no post has been created with 'Content Display' Block then click 'Add New' button > click' 'Add' > search 'Content Display'  > click 'Content Display'
5. Must be in 'Masonry View'
6. Decrease number of items in 'Block' tab on right to 1 then increase to 2
7. Observe main work area

**Expected behavior**
When increasing the number of viewable items, one would expect the next post to appear to the right of the first/previous post.

**Screenshots**

https://user-images.githubusercontent.com/79052272/120011663-cae87480-bf9b-11eb-9cf4-ba37361e4d19.mp4

Desktop:
Windows 10
Chrome
Version - 91.0.4472.77

**Additional context**
Having the Custom Field section active or not has no impact on this bug.

**Comment by htmgarcia** [comment]
@Bachynski same sugestion from #563

**Comment by htmgarcia** [comment]
Duplicated #549
