### ISSUE TITLE
Published post does not display the same content that is added before publishing.

### ISSUE THREAD

**Issue by sathyapriya91** [publishpress/PublishPress-Blocks#566]
**Describe the bug**

Newly published post does not display the same content that is added before publishing. The newly created post is added to the content after publishing.

**To Reproduce**

1. Open WordPress and create a new post
2. Give a title to that post
3. Select Add Block -> Content Display
4. Publish the created post
5. View the post just published

**Expected behavior**
The post should display only the items that is added before publishing. The post should not display the same post in the content after publishing.

**Screenshots**
![After publishing](https://user-images.githubusercontent.com/83974581/120036277-bf557780-bfb4-11eb-8dd0-c8d2a82a4059.JPG)
![Before publishing](https://user-images.githubusercontent.com/83974581/120036279-bfee0e00-bfb4-11eb-9e68-c477131a303c.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Chrome
 - Version 6.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by htmgarcia** [comment]
@sathyapriya91 in Filters planel look for "Exclude current post". Please enable it and should remove the post.
