### ISSUE TITLE
In 'sliderview', contents in the first block slides automatically when Autoplay is OFF

### ISSUE THREAD

**Issue by sathyapriya91** [publishpress/PublishPress-Blocks#569]
**Describe the bug**
When the Slider view has two added blocks, Contents in the first block slides automatically even when Autoplay is turned OFF.

**To Reproduce**
1. Open WordPress and create a new page
2. Give a title to that post
3. Select Add Block -> Content Display
4. Select "Slider View" (Keep Autoplay OFF)
5. Select Add Block -> Content Display again
6. Select "Slider View"
7. In "Slider View Settings", Select Autoplay ON
8. Publish the page and observe the result in View page

**Expected behavior**
Contents in the first block slides should not perform auto play when Autoplay is OFF.

**Screenshots**
![Autoplay](https://user-images.githubusercontent.com/83974581/120235764-9d0b6600-c20f-11eb-9fa2-10b54bf0a3ef.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Chrome
 - Version 6.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by htmgarcia** [comment]
@sathyapriya91 I confirm the issue. Thanks!
