### ISSUE TITLE
Need a clear way to delete unwanted content or blocks instead of deleting entire posts and starting from scratch

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#571]
While I was creating a  post using a "Content Display" Block when I accidentally created a duplicate Block in the same post. My first instinct, because it seems that their is a lot of functionality with the post editor already, that there was a 'button' to delete content within the post. Just like there is an option to delete the entire post all together in the 'Preferences' panel on the right. However I did not find such button, at least not easily identifiable if there is one. I sat on the situation for a few hours then a thought of simply just selecting the Block and using the 'delete' key came to mind, and solved my issue.

**Describe the solution you'd like**
Just like there is a 'button' to delete the entire post, maybe integrate something similar for deleting content of posts as well.

**Describe alternatives you've considered**
Include how to delete undesirable content in a post instead of having to delete the entire post and start from scratch.

**Comment by htmgarcia** [comment]
Removing a block is a feature that belongs to the Gutenberg core.
