### ISSUE TITLE
Change "Access" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#573]
Can we remove "Author" and "Date"? What we need is "Users" and "Roles"?

<img width="875" alt="Screen Shot 2021-06-02 at 7 19 34 PM" src="https://user-images.githubusercontent.com/3868028/120567482-87489d00-c3d7-11eb-9aca-e26de8c611f5.png">

**Comment by htmgarcia** [comment]
All set.
![Screen Shot 2021-06-03 at 16 54 14](https://user-images.githubusercontent.com/4999794/120717066-94739380-c48c-11eb-8990-6f844e09ecd0.png)
