### ISSUE TITLE
Layout changes for Block Access

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#574]
![screen](https://user-images.githubusercontent.com/3868028/120567751-148bf180-c3d8-11eb-924d-61873036557b.jpg)

**Comment by htmgarcia** [comment]
@stevejburge current look:
![Screen Shot 2021-06-03 at 13 43 36](https://user-images.githubusercontent.com/4999794/120696181-dba05b00-c471-11eb-91c9-535020f86668.png)

The title heading is removed. A placeholder will be displayed when title is empty:
![Screen Shot 2021-06-03 at 13 43 44](https://user-images.githubusercontent.com/4999794/120696196-dfcc7880-c471-11eb-9215-5df0c78467d5.png)
