### ISSUE TITLE
'Number of Items' in Post Settings overrides desired 'Newspaper View' settings.

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#577]
**Describe the bug**
When I increased the number of posts to show in the 'Content Display' block to 6 and had the 'Newspaper View' option of 1 main post and 1 side post selected it still showed the 1 main post but increased the displayed side posts to 5. 6 in total.

**To Reproduce**
1. Go to a created post with a "Content Display' Block or create on
2. In selector mode Click on desired 'Content Display' Block > Newspaper View
3. In Block editor window select desired 'Newspaper View' setting (any will do)
4. Scroll down to 'Post Settings' > Increase 'Number of Items' to anything greater than selected "Newspaper View Setting' describes
5. Observe number of posts in main window.

**Expected behavior**
When a 'Newspaper View Setting' ratio of 1:1, or 1:2 or 1:3, etc. is selected, regardless of how many 'Number of Items' are set the ratio should be hard set.

**Screenshots**
![Settings not working](https://user-images.githubusercontent.com/79052272/120845165-ac4f2400-c52d-11eb-82ee-1cdde401f5ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 91.0.4472.77

**Comment by htmgarcia** [comment]
@Bachynski number of items is not related to Frontpage view as described in Expected behavior. Not a bug.
