### ISSUE TITLE
Option to not display placeholder featured image

### ISSUE THREAD

**Issue by karinadmi** [publishpress/PublishPress-Blocks#583]
In the Display Settings, there is an option to show featured image for all posts, for x number of posts, or not to show it at all. 
But in the scenario where the user wants to show the featured images, but one of the posts does not have it,  a grey placeholder appears. 
I would suggest maybe to remove the placeholder image for the posts without images? Maybe the feature does exist already, but I was not able to find it.

![image](https://user-images.githubusercontent.com/47224335/121114122-278c3080-c7e1-11eb-9030-3c2d6474d388.png)

**Comment by htmgarcia** [comment]
@karinadmi maybe as an option like "Only when exists" here:
![Screen Shot 2021-06-08 at 13 22 35](https://user-images.githubusercontent.com/4999794/121237422-aa9e9c80-c85c-11eb-889f-d44365fe376e.png)

**Comment by htmgarcia** [comment]
Decide a slight different approach:
![Screen Shot 2021-06-22 at 18 40 52](https://user-images.githubusercontent.com/4999794/123013243-76ad9600-d389-11eb-8899-0ea058a33e87.png)
