### ISSUE TITLE
Addition of an equal height to each post component

### ISSUE THREAD

**Issue by karinadmi** [publishpress/PublishPress-Blocks#584]
In Grid and Front Page views the posts may appear slightly disorganized(in the case where some posts have bigger images than other posts or some do not have any images) and therefore it might be harder to follow the content or It could take a longer time for the user to configure the page.
I would suggest aligning the headers and adding equal heights to each post component, so that way they would appear more organized and easier to follow. 
I have attached a few examples below:
Ipad_>Grid Setting
![image](https://user-images.githubusercontent.com/47224335/121117328-f5c99880-c7e5-11eb-914d-84f540c9715b.png)

Desktop -> FrontPage View -> 5 Columns Setting
![image](https://user-images.githubusercontent.com/47224335/121117829-d2ebb400-c7e6-11eb-8985-b553dd476aba.png)

**Comment by htmgarcia** [comment]
@karinadmi In see your point, however this one is a bit tricky. We'll reconsider based on user feedback.
