### ISSUE TITLE
Keeping the content consistent throughout the list view 

### ISSUE THREAD

**Issue by karinadmi** [publishpress/PublishPress-Blocks#585]
In the List View, for the posts with the featured images, the featured image is being placed on the left and the content description on the right. Therefore the posts without the featured image appear to be not indented/ shifted to the left.
For the consistency within the List View I would suggest  :
1. Switching the spots for the image and the content description 
![image](https://user-images.githubusercontent.com/47224335/121119458-a71dfd80-c7e9-11eb-95be-e38d684ef995.png)

2. Indenting the posts without the image in order to match with the rest 
![image](https://user-images.githubusercontent.com/47224335/121119416-8e154c80-c7e9-11eb-9849-cb13a85daf02.png)

**Comment by htmgarcia** [comment]
Closing in favor of #497
