### ISSUE TITLE
Automatically adjust 'Number of items' based on the selected Newspaper layout

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#586]
**Is your feature request related to a problem? Please describe.**
When in 'Newspaper View' the editor window shows several templates. Many of them are the same but just show what the layout is supposed to look like when you increase the number of viewable posts. If the slider isn't supposed to affect the Newspaper view settings then why, when I select an option such as the leading post on the left and 3 additional posts on the right, do 5 additional posts show up instead when the slider is set to 6? Why have so many templates if they don't set the final layout?

**Describe the solution you'd like**
Disable the 'Number of items" slider and make the selection of 'Newspaper View Settings' templates set the final layout.

**Describe alternatives you've considered**
Or have one template per layout.

**Additional context**
![Newspaper View Suggestion](https://user-images.githubusercontent.com/79052272/121219771-46baaa80-c841-11eb-9013-38032a7d58c0.png)

**Comment by htmgarcia** [comment]
@Bachynski the layouts are just a visual example of the expected result. The number of items do its job.

This feedback makes me wonder if we should change the "Number of items" automatically based on the selected view?

**Comment by Bachynski** [comment]
@htmgarcia That is a good solution.

**Comment by htmgarcia** [comment]
When creating a new block and choosing Newspaper view, the items are still 8 instead of being 4 due the default layout.
