### ISSUE TITLE
Would it be possible to make the first frame or a snapshot of a video a featured image?

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#587]
**Is your feature request related to a problem? Please describe.**
I uploaded a video to one of my posts and had a thought. The first frame of the video makes for a good static image after seeing the very ordinary and bland 'grey mountain' default image for displaying featured image setting.

**Describe the solution you'd like**
Maybe have a 'check box' option to set video as featured image and that takes the first frame or a snapshot of the video and makes it into a static image for said featured image.

**Describe alternatives you've considered**
There might be easier ways but can't think of them atm.

**Additional context**

**Comment by htmgarcia** [comment]
@Bachynski is still easier to just upload a custom capture of the video. An automatic capture of the first frame may not match what the post/video reflects.
