### ISSUE TITLE
'Add Block' button remains visible in 'Tablet' or 'Mobile' Preview after scrolling past it.

### ISSUE THREAD

**Issue by Bachynski** [publishpress/PublishPress-Blocks#590]
**Describe the bug**
While in 'Tablet' or 'Mobile' preview clicking the scroll bar for the tablet or mobile preview pane reveals a small, black, square 'Add Block' button that remains visible even after scrolling past it in the editor window.

**To Reproduce**
1. Go to post with a 'Content Display' block
2. Using 'Select Mode' choose any View option
3. Click 'Preview' Tab and choose either 'Tablet' or 'Mobile'
4. Click tablet or mobile scroll bar
5. If not already scroll down editor window until only part of the Preview pane is visible
6. Scroll Preview pane and observe 'Add Block' button position

**Expected behavior**
When scrolling the 'Add Block' button should disappear along with the content as it passes the bottom of the Preview Pane.

**Screenshots**

https://user-images.githubusercontent.com/79052272/121389711-eb082400-c909-11eb-8391-b8a157234d85.mp4

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 91.0.4472.77

**Additional context**

**Comment by htmgarcia** [comment]
@Bachynski that add-block button belongs to Gutenberg editor, not PublishPress Blocks.
