### ISSUE TITLE
Testimonial Block shows HTLM Code

### ISSUE THREAD

**Issue by RealKolago** [publishpress/PublishPress-Blocks#672]
Testimonial Block shows HTLM Code

**To Reproduce**
1. Go to 'https://www.raumfahrer.net/verein-raumfahrer-net-e-v/vorstand-raumfahrer-net-e-v/'

This display error occurs in both Firefox and MS Edge.
OS is Windows 10 21H1

WP Theme is: Astra Version: 3.6.5 
PublishPress Blocks Version 2.9.1
WordPress Version: 5.8

**Comment by htmgarcia** [comment]
@RealKolago I confirm the issue. Thanks for reporting!

**Comment by RealKolago** [comment]
Thanks for the quick fix!

**Comment by RealKolago** [comment]
Is not fixed in 2.9.2!

**Comment by htmgarcia** [comment]
@RealKolago edit the page where you inserted the block and update. It should fix the result in frontend.

**Comment by RealKolago** [comment]
yes! works now.
