### ISSUE TITLE
Upgrade to Pro Menu Link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#673]
Let's add a promo screen here:
<img width="319" alt="Screen Shot 2021-07-26 at 2 29 24 PM" src="https://user-images.githubusercontent.com/3868028/127040587-5455fcd1-d186-4775-9067-bf4f877a8c01.png">

**Comment by htmgarcia** [comment]
@stevejburge starter proposal:
<img width="1422" alt="Screen Shot 2021-07-26 at 16 19 33" src="https://user-images.githubusercontent.com/4999794/127060729-dbff0374-4f2f-4937-a874-cf63a0391ce3.png">

**Comment by stevejburge** [comment]
@htmgarcia Looks good to me. It's a reminder that we should add more features to Pro
