### ISSUE TITLE
Rethink Block Access

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#674]
@stevejburge Block Access is a useful feature we can optimize and make more visible.
Is probably some users are not aware of Block Access due is located outside the Gutenberg editor (in Blocks > Block Access). If we move this feature to post editor, it will stand out. A second idea is to replace profiles with user roles (enable/disable access by user role), in addition, when managing block access directly in post editor, it will trigger all the plugin's blocks.
![Screen Shot 2021-07-27 at 19 37 41](https://user-images.githubusercontent.com/4999794/127245493-7d2d6492-8b85-4d07-b978-44b598dde5d4.png)

**Comment by htmgarcia** [comment]
We can rethink new Pro features to be available/promoted in Gutenberg editor instead of living in a separate Blocks menu.

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

I'm not sure about the button inside the post editor.

However the user roles idea is solid. We could approach this more like the "PublishPress Capabilities" screens.

**Comment by htmgarcia** [comment]
@stevejburge current progress. The screen is the same as profiles, however now we use user roles
![Screen Shot 2021-08-02 at 17 06 44](https://user-images.githubusercontent.com/4999794/127929924-0b7a4349-c7fb-4ec1-8e77-cef2882ce7ad.png)
:

**Comment by stevejburge** [comment]
@htmgarcia Yes. that's a good approach.

Maybe in the future, we can bring the main "Capabilities" screen in a similar direction.

**Comment by htmgarcia** [comment]
@stevejburge current progress includes automatic migration from active/inactive blocks for each user role from the most recent profile to the new block access approach. The assignment that will be lost in the process is about specific users.

**Comment by stevejburge** [comment]
thanks @htmgarcia. I wouldn't worry too much about block access for single users. It's a little-used feature
