### ISSUE TITLE
Blocks get their settings confused if they are duplicated

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#68]
If you add multiple Advanced Icon blocks, they get mixed up. You can see this on our demo site:

Admin:
<img width="935" alt="Screen Shot 2020-06-27 at 8 20 44 AM" src="https://user-images.githubusercontent.com/3868028/85922150-1efc4d80-b84f-11ea-8469-d48028679497.png">

Frontend:
<img width="869" alt="Screen Shot 2020-06-27 at 8 21 01 AM" src="https://user-images.githubusercontent.com/3868028/85922154-26235b80-b84f-11ea-8ef3-86fb6c0529de.png">

**Comment by stevejburge** [comment]
The same happens with buttons. I can only choose one color and that applies to all blocks:
<img width="317" alt="Screen Shot 2020-12-08 at 3 14 12 PM" src="https://user-images.githubusercontent.com/3868028/101536487-106ea200-3968-11eb-9954-00cff0ee5d56.png">

**Comment by htmgarcia** [comment]
This has been fixed in 2.5.3
