### ISSUE TITLE
Advanced Image blocks duplicated ID

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#69]
This seems to be related to https://github.com/Advanced-Gutenberg/advg/issues/68

The opacity settings for Advanced Image blocks seem to get mixed up. You can see this in our "Advanced Image" demo.

One block has this setting:
<img width="252" alt="Screen Shot 2020-06-27 at 8 30 36 AM" src="https://user-images.githubusercontent.com/3868028/85922341-81098280-b850-11ea-8f80-76039eb60c5f.png">

But the last block on the screen has this setting:
<img width="235" alt="Screen Shot 2020-06-27 at 8 31 04 AM" src="https://user-images.githubusercontent.com/3868028/85922353-8e267180-b850-11ea-940a-8fbee5b8538f.png">

The last block always wins

**Comment by htmgarcia** [comment]
@stevejburge I tested and wasn't able to reproduce the issue, however I do notice the block ID is duplicated. This happens only when duplicating the block.

**Comment by stevejburge** [comment]
@htmgarcia Yes, that might be the same bug
