### ISSUE TITLE
Count up symbols don't display under the numbers

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#70]
You can see this on our demo site:

Admin area:
<img width="1079" alt="Screen Shot 2020-06-28 at 10 18 06 AM" src="https://user-images.githubusercontent.com/3868028/85950097-ae296400-b928-11ea-9d63-5d2c68fb80f9.png">

Frontend:
<img width="858" alt="Screen Shot 2020-06-28 at 10 18 18 AM" src="https://user-images.githubusercontent.com/3868028/85950101-b5507200-b928-11ea-9a11-b192f7c6e91e.png">

**Comment by htmgarcia** [comment]
@stevejburge according to this:
<img width="254" alt="Screen Shot 2021-02-11 at 12 51 50" src="https://user-images.githubusercontent.com/4999794/107684085-f56e2600-6c67-11eb-9e10-e675110448c3.png">
and the gif from our docs page: https://publishpress.com/knowledge-base/count-up-block/ - the expected result is how looks in front. The signs should be displayed on the same line, not below/above.

**Comment by htmgarcia** [comment]
Fix:
<img width="906" alt="Screen Shot 2021-02-11 at 13 15 59" src="https://user-images.githubusercontent.com/4999794/107686842-51867980-6c6b-11eb-9649-1c761b328b9d.png">
