### ISSUE TITLE
Images Slider inside Advanced Tabs

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#71]
Images Slider inside inactive tabs doesn't work. e.g. Place 3 Images Slider blocks in 3 tabs from an Advanced Tabs block.   The first tab will load fine, but clicking on the other two won't display correctly the Images Slider blocks.
<img width="719" alt="Screen Shot 2020-07-02 at 11 52 56" src="https://user-images.githubusercontent.com/4999794/86388810-05963f80-bc5b-11ea-972e-160ae67b2ea1.png">
<img width="723" alt="Screen Shot 2020-07-02 at 11 53 02" src="https://user-images.githubusercontent.com/4999794/86388859-15ae1f00-bc5b-11ea-9132-6048bc29ce99.png">

____
Related HS ticket: https://secure.helpscout.net/conversation/1208229548/122316?folderId=3865380

**Comment by cityy** [comment]
Hey, I just stumbled upon this problem today. What is causing this? Is there any potential workaround fix that one could deploy like triggering a resize event on a slider container?

**Comment by htmgarcia** [comment]
Hi @cityy, this area is mainly for bug reports and improvements.

Would you mind sending us a support ticket [from our contact page](https://advancedgutenberg.com/) with all the most possible details?

**Comment by htmgarcia** [comment]
A new user report: https://secure.helpscout.net/conversation/1956412259/165515?folderId=4022715
