### ISSUE TITLE
Some blocks are not available

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#754]
Custom Blocks from Genesis Custom Blocks are not available to insert either in Block Access.
https://wordpress.org/support/topic/genesis-custom-blocks-gets-hidden/

**Comment by stevejburge** [comment]
@htmgarcia the same thing happens with PublishPress Series and TaxoPress

We think it's to do with legacy widgets

**Comment by htmgarcia** [comment]
@stevejburge legacy widgets seems to be a different issue. 
Opened an issue #756

**Comment by htmgarcia** [comment]
Duplicated issue. Refer to #755
