### ISSUE TITLE
Blocks with icons detected as typeof function triggers an error

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#755]
It happens with blocks such as Genesis Custom Blocks:
```
Uncaught (in promise) TypeError: savedIcon.prototype is undefined
    jsx editor.jsx:81
```
It causes the block not being listed in the editor either Block Access.

Related to #754

**Comment by htmgarcia** [comment]
@contactashish13 

1. Install and activate Genesis Custom Blocks
2. Go to Custom Blocks menu and publish the "Example Block"
3. Go to post edit

## Expected result:

The "Example Block" should be available to insert.

## Actual result:

The "Example Block" is not available.

The issue seems to be that the block doesn't have an icon available in the object and falls into `typeof function` which triggers an error in console. Please refer to this code involved: https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/js/editor.jsx#L57-L86

## Block with icon:
```
{
    name: "category/block-name",
    title: "Block Name",
    icon: {
        src: "[svg]"
    },
    category: "category-block"
}
```

## Block without icon:
```
{
    name: "category/block-name",
    title: "Block Name",
    category: "category-block"
}
```

**Comment by htmgarcia** [comment]
This solution https://github.com/publishpress/PublishPress-Blocks/pull/787 requires more debugging with third party plugins, including Genesis Custom Blocks.

**Comment by dipskakadiya** [comment]
Custom block with Dashicon showing error, 
`TypeError: Cannot read properties of undefined (reading 'render')` 

DashIcon prototype doesn't have render method because of that it's breaking functionality 

Ref code: update-block-list.js
```if (typeof savedIcon === 'function') {
                if (!!savedIcon.prototype.render) {
                    blockItem.icon = wp.element.renderToString(wp.element.createElement(savedIcon));
                } else {
                    blockItem.icon = wp.element.renderToString(savedIcon());
                }

                blockItem.icon = blockItem.icon.replace(/stopcolor/g, 'stop-color');
                blockItem.icon = blockItem.icon.replace(/stopopacity/g, 'stop-opacity');
            }```

Solution : 
Need to update `savedIcon.prototype.render` with `savedIcon.prototype?.render`

**Comment by htmgarcia** [comment]
Thanks for jumping into discussion, @dipskakadiya !

We use the same code in [a second file](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/assets/js/editor.jsx#L66) that loads in Gutenberg editor. Unfortunately changing the line breaks the javascript compilation (npm):
```
if (!!savedIcon.prototype?.render) {
    // ...
}
```
