### ISSUE TITLE
Stackable blocks are not loading in the Editor when PublishPress Blocks is activated

### ISSUE THREAD

**Issue by legaspielaine** [publishpress/PublishPress-Blocks#781]
**Describe the bug**
When I activate PublishPress Blocks v.2.11.0 together with Stackable blocks, the stackable blocks are missing.

**To Reproduce**
1. Activate PublishPress 2.11.0 & Stackable 3.0.4
2. Add a new page then add Stackable blocks / check the appender
3. See error

Upon investigating, it seems like the issue comes from PublishPress blocks. Please see screenshots below:

**Screenshots**

![Screen Shot 2021-10-25 at 11 17 25 AM](https://user-images.githubusercontent.com/28699204/138630725-7e61bf93-5df1-4a9e-8eab-37066004258c.png)

![Screen Shot 2021-10-25 at 11 06 13 AM](https://user-images.githubusercontent.com/28699204/138630660-a0576249-aa69-412a-b9bb-1553f020066c.png)

**Additional context**

Tried fixing the issue by changing this line: `if (!! savedIcon.prototype.render)`  to `if (!! savedIcon.prototype && !! savedIcon.prototype.render )` in `block.js` - this fixed it

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 94.0.4606.81

**Comment by htmgarcia** [comment]
@legaspielaine Stackable 3.0.5 update fixed the incompatibility issue.
