### ISSUE TITLE
Errors on widgets screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#792]
Notice: Undefined index: administrator in wp-content/plugins/advanced-gutenberg/init.php on line 107
Warning: in_array() expects parameter 2 to be array, null given in /wp-content/plugins/advanced-gutenberg/init.php on line 107
Notice: Undefined index: administrator in /wp-content/plugins/advanced-gutenberg/init.php on line 108
Warning: in_array() expects parameter 2 to be array, null given in /wp-content/plugins/advanced-gutenberg/init.php on line 108
Warning: array_push() expects parameter 1 to be array, null given in /wp-content/plugins/advanced-gutenberg/init.php on line 11
<img width="1036" alt="Screen Shot 2021-11-29 at 12 48 01 PM" src="https://user-images.githubusercontent.com/3868028/143917641-d0abd97a-a724-42e4-9f92-7778873bf042.png">

**Comment by htmgarcia** [comment]
@stevejburge if you visit a post edit screen and come back to widgets screen, does the notice disappears?

**Comment by htmgarcia** [comment]
@stevejburge not able to reproduce in PHP 7 and 8, except the one about `wp_enqueue_script`.

**Comment by htmgarcia** [comment]
I was able to reproduce manually if I delete `advgb_blocks_user_roles` option.
