### ISSUE TITLE
HTML tag options for the Header in "Advanced Accordion" Block

### ISSUE THREAD

**Issue by seth8373** [publishpress/PublishPress-Blocks#80]
It would be good to be able to have the option to choose different text sizes (e.g. h1, h2, h3, p, etc) for the text in the header.
Currently, it's limited to just one size (i.e. h4):

![Advanced Accordion Header Text](https://user-images.githubusercontent.com/65332667/88345919-5225e580-cd04-11ea-8ef7-b65c070c2394.PNG)

**Comment by TeddyBears** [comment]
Hello, this request is in roadmap or not ? Force Hn to element it's also a problem for accessibility and SEO

**Comment by htmgarcia** [comment]
Hi @TeddyBears,
is in our to-do list.

**Comment by htmgarcia** [comment]
The tag heading options will be available in 2.8.0. The size request was moved to #580
