### ISSUE TITLE
Manual registration of core/legacy-widget is required?

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#828]

**Comment by htmgarcia** [comment]
Sometimes these two blocks are listed twice in Block Access:
![Screen Shot 2022-01-20 at 10 46 35](https://user-images.githubusercontent.com/4999794/150384675-522dc799-440a-4a5b-a0b1-11b637cc3d30.png)

**Comment by htmgarcia** [comment]
@stevejburge I propose to remove the manual registration of Legacy Widget; is very odd and we have a report of a conflict with plugins that uses legacy widgets in post edit. 

Instead we force this essential block to load as active always without option to disable.

**Comment by stevejburge** [comment]
@htmgarcia sure, go for it
