### ISSUE TITLE
Advanced Tabs - tab style should always be highlighted

### ISSUE THREAD

**Issue by neurocode-dev** [publishpress/PublishPress-Blocks#834]
**Describe the bug**
After choosing a tab style, when the user changes focus, the highlight showing the chosen tab style disappears. This is very confusing for users.

**To Reproduce**
1. Add Advanced Table Block.
2. Choose "tab style" option in sidebar
3. Click anywhere else in the window
4. Chosen tab style highlight disappears

**Screenshots**
Chosen style is highlighted
![Chosen style is highlighted](https://user-images.githubusercontent.com/81964027/150452414-605ea2d3-31eb-4f12-9528-cf4a04f27af5.png)

When the user moves focus away the chosen option is no longer visible
![When the user moves focus away the chosen option is no longer visible
](https://user-images.githubusercontent.com/81964027/150452662-a81e8ccd-4490-449d-ac35-4f99b67fc438.png)

**Expected behavior**
Chosen tab style should always be highlighted

**Comment by htmgarcia** [comment]
@neurocode-dev are you using a particular theme?
