### ISSUE TITLE
Pro features for Core blocks

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#891]
A few examples: 

- Heading block: new design options such as padding, margin, borders
- Table block: border, cell spacing
- Image block: new styles
- Calendar block: design options and styles
- Paragraph: Google font

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/0a2bd3e3d388eca9b367ba901a3f7fd4529f35b1

**Comment by htmgarcia** [comment]
Google Fonts support for headings and paragraphs preview:
![Screen Shot 2022-04-29 at 13 37 39](https://user-images.githubusercontent.com/4999794/166005868-dde99120-3073-4f5e-868b-012eb2c447bc.png)

**Comment by htmgarcia** [comment]
@stevejburge Google Fonts support for headings and paragraphs preview:
![Screen Shot 2022-04-29 at 13 37 39](https://user-images.githubusercontent.com/4999794/166005868-dde99120-3073-4f5e-868b-012eb2c447bc.png)

**Comment by stevejburge** [comment]
@htmgarcia Looks very useful

**Comment by htmgarcia** [comment]
Let's circle back later to include features for other core blocks.
