### ISSUE TITLE
Bulk toggle for block access

### ISSUE THREAD

**Issue by simea-simea** [publishpress/PublishPress-Blocks#950]
**Is your feature request related to a problem? Please describe.**
I often use PublishPress Blocks to block out most blocks, because clients only need text and images (example).

**Describe the solution you'd like**
In other plugins I use, there is often a button to toggle all (this example is dynamic.ooo for elementor): 
![image](https://user-images.githubusercontent.com/48213023/168777046-17ae01a5-732a-4ba5-a3cf-97a915c503d9.png)

**Describe alternatives you've considered**
At the moment I have to go through every User Role and make a choice for every single block, while often I turn off all blocks of a type (e.g. theme blocks). 

**Additional context**
Maybe also a button to turn off access to a certain block for all users would be handy, but that would be another story :) 
And: Thank you for your great work guys, you really make WP better for us and our clients!

**Comment by htmgarcia** [comment]
Hi @simea-simea,
thanks for your suggestion! We'll work on this feature.

**Comment by simea-simea** [comment]
How fast are you guys!? Thanks so much!

**Comment by htmgarcia** [comment]
We are happy to help, @simea-simea !
