### ISSUE TITLE
Offset first posts

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#972]
Setting to exclude first posts. 

Case scenario: when the content is splitted into two instances of Content Display. Both display the most recent posts, however the first block display only the 3 most recent through a specific view, while the second block display starting from 4th post through another view.

**Comment by htmgarcia** [comment]
@stevejburge I wonder if this should be a Free feature?

**Comment by stevejburge** [comment]
Sure, if it's easiest to include that way
