### ISSUE TITLE
Select specific posts may slow down the editor

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#980]
A call to the available posts by posts type, seems to cause a performance problem. For sites having thousands of posts, the editor may be slow and affect the update/save post button performance.

**Comment by htmgarcia** [comment]
@olatechpro the problem is that [this query](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/assets/blocks/recent-posts/block.jsx#L1742-L1745) return all the posts from the site. This works fine for small sites, however for sites with thousands of posts, it slow the editor while retrieving the posts.

A solution I was trying to achieve is making [this query](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/assets/blocks/recent-posts/block.jsx#L1742-L1745) return only the selected posts (from "Exclude these posts" and "Display these posts only" fields) and a few suggestions based on what we type on these fields.
![Screen Shot 2022-06-14 at 14 55 39](https://user-images.githubusercontent.com/4999794/173677126-4139e073-a499-45df-910f-017733b675bc.png)
![Screen Shot 2022-06-14 at 15 35 17](https://user-images.githubusercontent.com/4999794/173683763-c7dca480-0485-47f5-ba34-36ab11e1a66d.png)

Feel free to use [this branch](https://github.com/publishpress/PublishPress-Blocks/compare/develop...include-posts-fix?expand=1) that includes the search argument into the query, or your own branch based on master (not in develop).

**Comment by htmgarcia** [comment]
Dev docs: https://publishpress.github.io/docs/free-pro-versions/blocks

**Comment by olatechpro** [comment]
Thanks for the information @htmgarcia what version of npm are you using?

I'm getting some error while trying to install the plugin dependency and believe it may be related to the npm and node version on my laptop.

So, i can simply upgrade/downgrade to the version that's working @htmgarcia

**Comment by htmgarcia** [comment]
@olatechpro npm version 7.7.6

**Comment by olatechpro** [comment]
Thanks @htmgarcia

**Comment by htmgarcia** [comment]
@olatechpro I was able to figure out a partial solution, however there is an odd behavior when selecting posts from "Display these posts only" and "Exclude these posts" fields:
![false](https://user-images.githubusercontent.com/4999794/173942967-573af346-03e0-43d0-a0ef-131383270ae7.png)

Also sometimes the post suggestions come up but can't select any. This may happens when switching between adding posts from "Display these posts only", then clearing selection and choosing posts from "Exclude these posts", and vice versa.
![Screen Shot 2022-06-15 at 17 35 45](https://user-images.githubusercontent.com/4999794/173946598-56cb5983-9f08-4dfa-a34d-526df979b850.png)
