### ISSUE TITLE
Updated translation files

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#998]
Spanish, Italian and French

[Attachments.zip](https://github.com/publishpress/PublishPress-Blocks/files/9041487/Attachments.zip)
[Attachments(1).zip](https://github.com/publishpress/PublishPress-Blocks/files/9041488/Attachments.1.zip)
[Attachments(2).zip](https://github.com/publishpress/PublishPress-Blocks/files/9041489/Attachments.2.zip)

**Comment by htmgarcia** [comment]
@stevejburge the 3 zip contains different files, all for Italian

**Comment by htmgarcia** [comment]
@stevejburge 

Free version: updated translations for Spanish, Spanish (MX), Italian, Danish, Norwegian and French. In addition, added JSON translations for French, Danish and Norwegian (these applies to javascript content). https://github.com/publishpress/PublishPress-Blocks/commit/38ddf812e02b7025973cf19288c8d355670ad7d8

Pro version: setup a script to merge the free and pro translations. The only manual step is the MO files generation through Poedit. https://github.com/publishpress/PublishPress-Blocks-Pro/commit/23bd984467e8ac76b7871bb838579c02125e7f50

**Comment by stevejburge** [comment]
awesome, thanks @htmgarcia 

I think Angelo has been uploading the latest Spanish, French and Italian to WordPress.org 
https://translate.wordpress.org/projects/wp-plugins/advanced-gutenberg/

I'm asking him to add to Github in the future

**Comment by htmgarcia** [comment]
@stevejburge I already included those translations.
